blueprint: 1.0.0
name: block-storage
url: https://block-storage.magalu.cloud
version: 1.52.0
description: Operations for Block Storage API
components:
  schemas:
    VolumeAttachObject:
      type: object
      properties:
        block_storage_id:
          $ref: /block-storage/volumes/attach/parametersSchema/properties/id
        virtual_machine_id:
          $ref: /block-storage/volumes/attach/parametersSchema/properties/virtual_machine_id

  configsSchemas:
    default:
      $ref: /block-storage/volumes/get/configsSchema

children:
- name: volume-attachment
  description: Block Storage Volume Attachment
  isInternal: true
  children:

  - name: create
    description: Attach a volume to a virtual machine instance
    scopes:
    - "block-storage.write"

    parametersSchema:
      $ref: blueprint#/components/schemas/VolumeAttachObject
    configsSchema:
      $ref: blueprint#/components/configsSchemas/default
    resultSchema:
      $ref: blueprint#/components/schemas/VolumeAttachObject

    steps:
    - target: /block-storage/volumes/attach
      parameters:
        id: $.parameters.block_storage_id
        virtual_machine_id: $.parameters.virtual_machine_id

      check:
        errorMessageTemplate: |
          Virtual machine {{ .parameters.virtual_machine_id }} was not attached to block storage {{ .parameters.block_storage_id }}
        jsonPathQuery: |
          hasKey($.current.result, "attachment") && $.current.result.attachment[?(@.machine_id == $.parameters.virtual_machine_id)]

  - name: get
    description: Check if a volume is attached to a virtual machine instance
    scopes:
    - "block-storage.read"

    parametersSchema:
      $ref: blueprint#/components/schemas/VolumeAttachObject
    configsSchema:
      $ref: blueprint#/components/configsSchemas/default
    resultSchema:
      $ref: blueprint#/components/schemas/VolumeAttachObject

    result: | # the result values must match the parameters, so use directly:
      {
        "block_storage_id": $.parameters.block_storage_id,
        "virtual_machine_id": $.parameters.virtual_machine_id
      }

    steps:
    - target: /block-storage/volumes/get
      parameters:
        id: $.parameters.block_storage_id
      check:
        errorMessageTemplate: |
          Unable to find virtual machine {{ .parameters.virtual_machine_id }} in block storage {{ .parameters.block_storage_id }} attachments
        jsonPathQuery: |
          hasKey($.current.result, "attachment") && $.current.result.attachment[?(@.machine_id == $.parameters.virtual_machine_id)]

  # UPDATE: not available, it's present o cope with TerraForm's constraints until it's fixed
  - name: update
    description: Update a block storage volume attachment
    parametersSchema:
      $ref: /block-storage/volume-attachment/get/parametersSchema
    configsSchema:
      $ref: /block-storage/volume-attachment/get/configsSchema
    resultSchema:
      $ref: /block-storage/volume-attachment/get/resultSchema
    steps:
    - target: /block-storage/volume-attachment/get

  - name: delete
    description: Detach a volume from a virtual machine instance
    scopes:
    - "block-storage.write"

    confirm: |
      Deleting {{ .parameters.block_storage_id }} from {{ .parameters.virtual_machine_id }} cannot be undone.
      Confirm?

    parametersSchema:
      $ref: blueprint#/components/schemas/VolumeAttachObject
    configsSchema:
      $ref: blueprint#/components/configsSchemas/default
    resultSchema:
      $ref: blueprint#/components/schemas/VolumeAttachObject

    result: | # the result values must match the parameters, so use directly:
      {
        "block_storage_id": $.parameters.block_storage_id,
        "virtual_machine_id": $.parameters.virtual_machine_id
      }

    steps:
    - target: /block-storage/volumes/detach
      parameters:
        id: $.parameters.block_storage_id
        virtual_machine_id: $.parameters.virtual_machine_id

      check:
        errorMessageTemplate: |
          Virtual machine {{ .parameters.virtual_machine_id }} is still attached to block storage {{ .parameters.block_storage_id }}
        jsonPathQuery: |
          !hasKey($.current.result, "attachment") || $.current.result.attachment[?(@.machine_id != $.parameters.virtual_machine_id)]
