blueprint: 1.0.0
name: dbaas
url: https://dbaas.magalu.cloud
version: 1.13.2
description: Operations for DBaaS API

children:
  - name: backups
    description: Database backups management.
    children:
      - name: restore
        description: Restores a backup for an instance asynchronously
        positionalArgs: [instance_id, backup_id]
        parametersSchema:
          $ref: http://magalu.cloud/sdk#/dbaas/restores/create/parametersSchema
        configsSchema:
          $ref: http://magalu.cloud/sdk#/dbaas/restores/create/configsSchema
        resultSchema:
          $ref: http://magalu.cloud/sdk#/dbaas/restores/create/resultSchema

        steps:
          - target: /dbaas/restores/create
