blueprint: 1.0.0
name: network
url: https://network.magalu.cloud
version: 1.99.5
description: Operations for Network API
components:
  schemas:
    PublicIPAttachObject:
      type: object
      required:
        - public_ip_id
        - port_id
      properties:
        public_ip_id:
          $ref: /network/public_ips/attach/parametersSchema/properties/public_ip_id
        port_id:
          $ref: /network/public_ips/attach/parametersSchema/properties/port_id
    PortAttachObject:
      type: object
      required:
        - security_group_id
        - port_id
      properties:
        port_id:
          $ref: /network/ports/attach/parametersSchema/properties/port_id
        security_group_id:
          $ref: /network/ports/attach/parametersSchema/properties/security_group_id

  configsSchemas:
    default:
      $ref: /network/public_ips/get/configsSchema

children:
  - name: ports
    description: VPC Port
    children:
      - $ref: http://magalu.cloud/sdk#/network/vpcs/ports/create
        isInternal: false

      - name: security-group-attachment
        description: Manage the attachment between a Security Group and a Port
        isInternal: true
        children:
          - name: create
            description: Attach a Security Group to a Port
            scopes:
            - "network.write"

            parametersSchema:
              $ref: blueprint#/components/schemas/PortAttachObject
            configsSchema:
              $ref: blueprint#/components/configsSchemas/default
            resultSchema:
              $ref: blueprint#/components/schemas/PortAttachObject

            steps:
            - target: /network/ports/attach
              parameters:
                security_group_id: $.parameters.security_group_id
                port_id: $.parameters.port_id

            - target: /network/ports/get
              parameters:
                port_id: $.parameters.port_id
              check:
                errorMessageTemplate: |
                  Security Group {{ .parameters.security_group_id }} was not attached to Port {{ .parameters.port_id }}
                jsonPathQuery: |
                  hasKey($.current.result, "security_groups") && $.current.result.security_groups[?(@ == $.parameters.security_group_id)].length > 0
            links:
              get:
                target: /network/ports/security-group-attachment/get
                description: Check if this Security Group is attached to this Port
                parameters:
                  security_group_id: $.parameters.security_group_id
                  port_id: $.parameters.port_id

          - name: get
            description: Check if a Public IP is attached to a Port
            scopes:
            - "network.read"

            parametersSchema:
              $ref: blueprint#/components/schemas/PortAttachObject
            configsSchema:
              $ref: blueprint#/components/configsSchemas/default
            resultSchema:
              $ref: blueprint#/components/schemas/PortAttachObject

            steps:
            - target: /network/ports/get
              parameters:
                port_id: $.parameters.port_id
              retryUntil:
                maxRetries: 3
                interval: 5s
                jsonPathQuery: |
                  hasKey($.current.result, "security_groups") && $.current.result.security_groups[?(@ == $.parameters.security_group_id)].length > 0

              check:
                errorMessageTemplate: |
                  Security Group {{ .parameters.security_group_id }} is not attached to Port {{ .parameters.port_id }}
                jsonPathQuery: |
                  hasKey($.current.result, "security_groups") && $.current.result.security_groups[?(@ == $.parameters.security_group_id)].length > 0

          - name: delete
            description: Detach a Security Group from a Port
            scopes:
            - "network.write"

            confirm: |
              Detaching Security Group {{ .parameters.security_group_id }} from Port {{ .parameters.port_id }}. Confirm?

            parametersSchema:
              $ref: blueprint#/components/schemas/PortAttachObject
            configsSchema:
              $ref: blueprint#/components/configsSchemas/default
            resultSchema:
              $ref: blueprint#/components/schemas/PortAttachObject

            result: | # the result values must match the parameters, so use directly:
              {
                "security_group_id": $.parameters.security_group_id,
                "port_id": $.parameters.port_id,
              }

            steps:
            - target: /network/ports/detach
              parameters:
                security_group_id: $.parameters.security_group_id
                port_id: $.parameters.port_id

  - name: public_ips
    description: VPC Public IPs
    children:
      - $ref: http://magalu.cloud/sdk#/network/vpcs/public-ips/create
        isInternal: false
      - name: port-attachment
        description: Manage the attachment between a Public IP and a Port
        isInternal: true
        children:
          - name: create
            description: Attach a Public IP to a Port
            scopes:
            - "network.write"

            parametersSchema:
              $ref: blueprint#/components/schemas/PublicIPAttachObject
            configsSchema:
              $ref: blueprint#/components/configsSchemas/default
            resultSchema:
              $ref: blueprint#/components/schemas/PublicIPAttachObject

            steps:
            - target: /network/public_ips/attach
              parameters:
                public_ip_id: $.parameters.public_ip_id
                port_id: $.parameters.port_id

            - target: /network/public_ips/get
              parameters:
                public_ip_id: $.parameters.public_ip_id
              check:
                errorMessageTemplate: |
                  PublicIP {{ .parameters.public_ip_id }} was not attached to Port {{ .parameters.port_id }}
                jsonPathQuery: |
                  hasKey($.current.result, "port_id") && $.current.result.port_id == $.current.parameters.port_id
            links:
              get:
                target: /network/public_ips/port-attachment/get
                description: Check if this Public IP is attached to a Port
                parameters:
                  public_ip_id: $.parameters.public_ip_id
                  port_id: $.parameters.port_id

          - name: get
            description: Check if a Public IP is attached to a Port
            scopes:
            - "network.read"

            parametersSchema:
              $ref: blueprint#/components/schemas/PublicIPAttachObject
            configsSchema:
              $ref: blueprint#/components/configsSchemas/default
            resultSchema:
              $ref: blueprint#/components/schemas/PublicIPAttachObject

            steps:
            - target: /network/public_ips/get
              parameters:
                public_ip_id: $.parameters.public_ip_id
              retryUntil:
                maxRetries: 3
                interval: 5s
                jsonPathQuery: |
                  hasKey($.current.result, "port_id") && $.current.result.port_id == $.current.parameters.port_id

              check:
                errorMessageTemplate: |
                  PublicIP {{ .parameters.public_ip_id }} is not attached to Port {{ .parameters.port_id }}
                jsonPathQuery: |
                  hasKey($.current.result, "port_id") && $.current.result.port_id == $.current.parameters.port_id

          - name: delete
            description: Detach a Public IP from a Port
            scopes:
            - "network.write"

            confirm: |
              Detaching PublicIP {{ .parameters.public_ip_id }} from Port {{ .parameters.port_id }}. Confirm?

            parametersSchema:
              $ref: blueprint#/components/schemas/PublicIPAttachObject
            configsSchema:
              $ref: blueprint#/components/configsSchemas/default
            resultSchema:
              $ref: blueprint#/components/schemas/PublicIPAttachObject

            result: | # the result values must match the parameters, so use directly:
              {
                "public_ip_id": $.parameters.public_ip_id,
                "port_id": $.parameters.port_id
              }

            steps:
            - target: /network/public_ips/detach
              parameters:
                public_ip_id: $.parameters.public_ip_id
                port_id: $.parameters.port_id

  - name: rules
    description: VPC Rules
    children:
      - $ref: http://magalu.cloud/sdk#/network/security_groups/rules/create
        isInternal: false

      - $ref: http://magalu.cloud/sdk#/network/security_groups/rules/list
        isInternal: false

  # - name: subnets
  #   description: VPC Subnets
  #   children:
  #     - $ref: http://magalu.cloud/sdk#/network/vpcs/subnets/create
  #       isInternal: false

  #     - $ref: http://magalu.cloud/sdk#/network/vpcs/subnets/list
  #       isInternal: false
