blueprint: 1.0.0
name: network
url: https://network.magalu.cloud
version: 1.99.5
description: Operations for Network API

children:
  - name: public_ip
    description: VPC Public IPs
    children:
      - $ref: http://magalu.cloud/sdk#/network/vpc/public-ips/create
        isInternal: false

  - name: rule
    description: VPC Rules
    children:
      - $ref: http://magalu.cloud/sdk#/network/security_group/rules/create
        isInternal: false

      - $ref: http://magalu.cloud/sdk#/network/security_group/rules/list
        isInternal: false

  - name: subnets
    description: VPC Subnets
    children:
      - $ref: http://magalu.cloud/sdk#/network/vpc/subnets/create
        isInternal: false

      - $ref: http://magalu.cloud/sdk#/network/vpc/subnets/list
        isInternal: false
