# This file is to be merged on top of mgc/cli/openapis/vpc.openapi.yaml
# using yaml_merge.py
# NOTE: Lists are merged by their indexes, be careful with parameters, tags and such!
# to keep it sane, keep some list item identifier (ex: "name") and add extra properties,
# such as "x-mgc-name" or "x-mgc-description"

servers:
-   url: https://{env}/{region}/volume
    variables:
        region:
            description: Region to reach the service
            default: br-ne-1
            enum:
            - br-ne-1
            - br-se-1
            x-mgc-transforms:
            -   type: translate
                translations:
                -   from: br-ne1
                    to: br-ne-1
                -   from: br-se1
                    to: br-se-1
        env:
            description: Environment to use
            default: api.magalu.cloud
            enum:
            - api.magalu.cloud
            - api.pre-prod.jaxyendy.com
            x-mgc-transforms:
            -   type: translate
                translations:
                -   from: prod
                    to: api.magalu.cloud
                -   from: pre-prod
                    to: api.pre-prod.jaxyendy.com

paths:
    /v0/volumes:
        get:
            x-mgc-description: List all Block Storage volumes
        post:
            x-mgc-description: Create a Block Storage volume
            responses:
                '201':
                    links:
                        get:
                            operationRef: '#/paths/~1v0~1volumes~1{id}/get'
                            description: Read Block Storage volume
                            parameters:
                                id: $response.body#/id
                        update:
                            operationRef: '#/paths/~1v0~1volumes~1{id}/patch'
                            description: Update Block Storage volume
                            parameters:
                                id: $response.body#/id
                        delete:
                            operationRef: '#/paths/~1v0~1volumes~1{id}/delete'
                            description: Delete Block Storage volume
                            parameters:
                                id: $response.body#/id
    /v0/volumes/{id}:
        get:
            x-mgc-description: Get a Block Storage volume details
            responses:
                '200':
                    links:
                        update:
                            operationRef: '#/paths/~1v0~1volumes~1{id}/patch'
                            description: Update Block Storage volume
                            parameters:
                                id: $request.path.id
                        delete:
                            operationRef: '#/paths/~1v0~1volumes~1{id}/delete'
                            description: Delete Block Storage volume
                            parameters:
                                id: $request.path.id
        delete:
            x-mgc-description: Delete a Block Storage volume
        patch:
            x-mgc-description: Update a Block Storage volume
            responses:
                '200':
                    links:
                        get:
                            operationRef: '#/paths/~1v0~1volumes~1{id}/get'
                            description: Read Block Storage volume
                            parameters:
                                id: $request.path.id
                        delete:
                            operationRef: '#/paths/~1v0~1volumes~1{id}/delete'
                            description: Delete Block Storage volume
                            parameters:
                                id: $request.path.id
    /v0/volumes/{id}/attach/{virtual_machine_id}:
        post:
            x-mgc-name: attach
            responses:
                '200':
                    links:
                        delete-connection:
                            description: Detach from a Virtual Machine instance
                            operationRef: '#/paths/~1v0~1volumes~1{id}~1detach~1{virtual_machine_id}/post'
                            parameters:
                                id: $request.path.id
                        get-connection:
                            description: Check if block storage is attached to Virtual
                                Machine instance
                            operationRef: '#/paths/~1v0~1volumes/get'
                            parameters:
                                id: $request.path.id
                            x-mgc-wait-termination:
                                maxRetries: 1
                                interval: 5s
                                jsonPathQuery: $.result.attachments[?(@.virtual_machine_id == $.owner.parameters.virtual_machine_id)]
    /v0/volumes/{id}/detach/{virtual_machine_id}:
        post:
            x-mgc-name: detach
    /v0/snapshots:
        post:
            responses:
                '202':
                    links:
                        delete:
                            operationRef: '#/paths/~1v0~1snapshots~1{snapshot_id}/delete'
                            description: Delete snapshot
                            parameters:
                                snapshot_id: $response.body#/id
    /v0/snapshots/{snapshot_id}:
        post:
            x-mgc-name: restore
    /v0/volume_types_all:
        get:
            x-mgc-hidden: true


tags:
-   name: healthchecks
    description: healthchecks
    x-mgc-hidden: true
-   name: usage
    description: usage
-   name: snapshots
    description: snapshots
-   name: volume-types
    description: volume types
-   name: block-storage
    x-mgc-description: Block Storage Volume Resources
    x-mgc-name: volume
