# This file is to be merged on top of mgc/cli/openapis/vpc.openapi.yaml
# using yaml_merge.py
# NOTE: Lists are merged by their indexes, be careful with parameters, tags and such!
# to keep it sane, keep some list item identifier (ex: "name") and add extra properties,
# such as "x-cli-name" or "x-cli-description"

servers:
-   url: https://api-block-storage{env}.{region}.jaxyendy.com
    variables:
        region:
            description: Region to reach the service
            default: br-ne-1
            enum:
            - br-ne-1
            - br-ne-2
            - br-se-1
        env:
            description: Environment to use
            default: ''
            enum:
            - ''
            - .pre-prod
            x-cli-transforms:
            -   type: translate
                translations:
                -   from: prod
                    to: ''
                -   from: pre-prod
                    to: .pre-prod

paths:
    /v0/volumes:
        get:
            x-cli-description: List all Block Storage volumes
        post:
            x-cli-description: Create a Block Storage volume
            responses:
                '200':
                    links:
                        read:
                            operationId: volume_details_v0_volumes__id__get
                            description: Read Block Storage volume
                            parameters:
                                id: $response.body#/id
                        update:
                            operationId: update_volume_v0_volumes__id__patch
                            description: Update Block Storage volume
                            parameters:
                                id: $response.body#/id
                        delete:
                            operationId: delete_volume_v0_volumes__id__delete
                            description: Delete Block Storage volume
                            parameters:
                                id: $response.body#/id
    /v0/volumes/{id}:
        get:
            x-cli-description: Get a Block Storage volume details
            responses:
                '200':
                    links:
                        update:
                            operationId: update_volume_v0_volumes__id__patch
                            description: Update Block Storage volume
                            parameters:
                                id: $request.path.id
                        delete:
                            operationId: delete_volume_v0_volumes__id__delete
                            description: Delete Block Storage volume
                            parameters:
                                id: $request.path.id
                        create/attach-to-vm:
                            description: Attach this BS Volume to a VM instance
                            operationId: attach_volume_v0_volumes__id__attach__virtual_machine_id__post
                            parameters:
                                id: $request.path.id
                        delete/attach-to-vm:
                            description: Detach this BS Volume to a VM instance
                            operationId: detach_volume_v0_volumes__id__detach__virtual_machine_id__post
                            parameters:
                                id: $request.path.id
                        read/attach-to-vm:
                            description: Check if this BS Volume is attached to a VM instance
                            operationId: volume_details_v0_volumes__id__get
                            parameters:
                                id: $request.path.id
                            x-cli-extra-parameters:
                                - name: virtual_machine_id
                                  required: true
                                  schema:
                                      type: string
                                      format: uuid
                            x-cli-wait-termination:
                                maxRetries: 2
                                intervalInSeconds: 5s
                                jsonPathQuery: $.result.attachments[?(@.virtual_machine_id == $.parameters.virtual_machine_id)]
        delete:
            x-cli-description: Delete a Block Storage volume
        patch:
            x-cli-description: Update a Block Storage volume
            responses:
                '200':
                    links:
                        read:
                            operationId: volume_details_v0_volumes__id__get
                            description: Read Block Storage volume
                            parameters:
                                id: $request.path.id
                        delete:
                            operationId: delete_volume_v0_volumes__id__delete
                            description: Delete Block Storage volume
                            parameters:
                                id: $request.path.id
    /v0/volumes/{id}/attach/{virtual_machine_id}:
        post:
            x-cli-name: attach
            responses:
                '200':
                    links:
                        delete:
                            description: Detach from a Virtual Machine instance
                            operationId: detach_volume_v0_volumes__id__detach__virtual_machine_id__post
                            parameters:
                                id: $path.id
                        read:
                            description: Check if block storage is attached to Virtual Machine instance
                            operationId: volume_details_v0_volumes__id__get
                            parameters:
                                id: $path.id
                            x-cli-wait-termination:
                                maxRetries: 2
                                intervalInSeconds: 15s
                                jsonPathQuery: $.result.attachments[*]
    /v0/volumes/{id}/detach/{virtual_machine_id}:
        post:
            x-cli-name: detach
    /v0/snapshots:
        post:
            responses:
                '202':
                    links:
                        delete:
                            operationId: delete_snapshot_v0_snapshots__snapshot_id__delete
                            description: Delete snapshot
                            parameters:
                                snapshot_id: $response.body#/id
    /v0/snapshots/{snapshot_id}:
        post:
            x-cli-name: restore


tags:
-   name: healthchecks
    description: healthchecks
    x-cli-hidden: true
-   name: usage
    description: usage
-   name: snapshots
    description: snapshots
-   name: volume-types
    description: volume types
-   name: block-storage
    x-cli-description: Block Storage Volume Resources
    x-cli-name: volume
