# This file is to be merged on top of mgc/cli/openapis/vpc.openapi.yaml
# using yaml_merge.py
# NOTE: Lists are merged by their indexes, be careful with parameters, tags and such!
# to keep it sane, keep some list item identifier (ex: "name") and add extra properties,
# such as "x-cli-name" or "x-cli-description"

servers:
-   url: https://api-block-storage{env}.{region}.jaxyendy.com
    variables:
        region:
            description: Region to reach the service
            default: br-ne-1
            enum:
            - br-ne-1
            - br-ne-2
            - br-se-1
        env:
            description: Environment to use
            default: ""
            enum:
            - ""
            - ".pre-prod"

paths:
    /v0/volumes:
        get:
            x-cli-description: List all Block Storage volumes
        post:
            x-cli-description: Create a Block Storage volume
    /v0/volumes/{id}:
        get:
            x-cli-description: Get a Block Storage volume details
        delete:
            x-cli-description: Delete a Block Storage volume
        patch:
            x-cli-description: Update a Block Storage volume

tags:
-   name: healthchecks
    description: healthchecks
    x-cli-hidden: true
-   name: usage
    description: usage
-   name: snapshots
    description: snapshots
-   name: volume-types
    description: volume types
-   name: block-storage
    x-cli-description: Block Storage Volume Resources
    x-cli-name: volume
