# This file is to be merged on top of mgc/cli/openapis/dbaas.openapi.yaml
# using yaml_merge.py
# NOTE: Lists are merged by their indexes, be careful with parameters, tags and such!
# to keep it sane, keep some list item identifier (ex: "name") and add extra properties,
# such as "x-mgc-name" or "x-mgc-description"
servers:
-   url: https://{env}/{region}/database
    variables:
        region:
            description: Region to reach the service
            default: br-ne-1
            enum:
            - br-ne-1
            - br-se1
            - br-mgl1
            x-mgc-transforms:
            -   type: translate
                allowMissing: true
                translations:
                -   from: br-ne1
                    to: br-ne-1
                -   from: br-mgl1
                    to: br-se-1
        env:
            description: Environment to use
            default: api.magalu.cloud
            enum:
            - api.magalu.cloud
            - api.pre-prod.jaxyendy.com
            x-mgc-transforms:
            -   type: translate
                translations:
                -   from: prod
                    to: api.magalu.cloud
                -   from: pre-prod
                    to: api.pre-prod.jaxyendy.com
paths:
    /v1/instances/{instance_id}/backups/{backup_id}:
        get:
            x-mgc-wait-termination:
                maxRetries: 20
                interval: 5s
                jsonPathQuery: $.status != PENDING && $.status != CREATING
    /v1/instances/{instance_id}:
        get:
            responses:
              '200':
                  links:
                      update/flavor_id:
                          operationId: instances_v1_resize
                          description: Resizes a database instance.
                          parameters:
                              instance_id: $request.path.instance_id
                          x-mgc-hidden: true
                      update/status/ACTIVE:
                          operationId: instances_v1_start
                          description: Starts a database instance.
                          parameters:
                              instance_id: $request.path.instance_id
                          x-mgc-hidden: true
                      update/status/STOPPED:
                          operationId: instances_v1_stop
                          description: Stops a database instance.
                          parameters:
                              instance_id: $request.path.instance_id
                          x-mgc-hidden: true
            x-mgc-wait-termination:
                maxRetries: 100
                interval: 20s
                jsonPathQuery: (hasKey($.result, "status")) && ($.result.status == "ACTIVE" || $.result.status == "STOPPED" || $.result.status == "ERROR")
    /v1/instances/{instance_id}/resize:
        post:
            responses:
              '200':
                  links:
                      get:
                          x-mgc-wait-termination:
                              maxRetries: 20
                              interval: 10s
                              jsonPathQuery: $.result.volume.size == $.owner.parameters.volume.size
    /v1/instances/{instance_id}/start:
        post:
            responses:
              '200':
                  links:
                      get:
                          x-mgc-wait-termination:
                              maxRetries: 20
                              interval: 10s
                              jsonPathQuery: $.result.status == "ACTIVE"
            x-mgc-name: start
    /v1/instances/{instance_id}/stop:
        post:
            responses:
              '200':
                  links:
                      get:
                          x-mgc-wait-termination:
                              maxRetries: 20
                              interval: 10s
                              jsonPathQuery: $.result.status == "STOPPED"
    /v1/replicas/{replica_id}:
        get:
            responses:
              '200':
                  links:
                      update/volume:
                          operationId: replica_resize_v1_replicas_post
                          description: Resizes a database instance.
                          parameters:
                              replica_id: $request.path.replica_id
                          x-mgc-hidden: true
                      update/status/ACTIVE:
                          operationId: replica_start_v1_replicas__replica_id__start_post
                          description: Start an instance replica.
                          parameters:
                              replica_id: $request.path.replica_id
                          x-mgc-hidden: true
                      update/status/STOPPED:
                          operationId: replica_stop_v1_replicas__replica_id__stop_post
                          description: Stop an instance replica.
                          parameters:
                              replica_id: $request.path.replica_id
                          x-mgc-hidden: true
    /v1/replicas/{replica_id}/resize:
        post:
            responses:
                '200':
                    links:
                        get:
                            x-mgc-wait-termination:
                                maxRetries: 20
                                interval: 5s
                                jsonPathQuery: $.result.flavor_id == $.owner.parameters.flavor_id
    /v1/replicas/{replica_id}/start:
        post:
            responses:
                '200':
                    links:
                        get:
                            x-mgc-wait-termination:
                                maxRetries: 20
                                interval: 5s
                                jsonPathQuery: $.result.status == "ACTIVE"
    /v1/replicas/{replica_id}/stop:
        post:
            responses:
                '200':
                    links:
                        get:
                            x-mgc-wait-termination:
                                maxRetries: 20
                                interval: 5s
                                jsonPathQuery: $.result.status == "STOPPED"
# ExclusiveMinimum must be replaced from number to boolean. JSON Schema new draft
# proposes as a number, but this is only available in OpenAPI 3.1.0. Since kin-openapi
# only supports up to 3.0.0, we need to patch to be a boolean
components:
    schemas:
        BackupDetailResponse:
            properties:
                db_size:
                    minimum: 0.0
                    exclusiveMinimum: true
                size:
                    minimum: 0.0
                    exclusiveMinimum: true
        InstanceCreateRequest:
            properties:
                name:
                    example: dbaas-name
                datastore_id:
                    example: 063f3994-b6c2-4c37-96c9-bab8d82d36f7
                flavor_id:
                    example: 8bbe8e01-40c8-4d2b-80e8-189debc44b1c
                user:
                    example: dbaas-user
                password:
                    example: dbaas-password
                backup_retention_days:
                    minimum: 0.0
                    exclusiveMinimum: true
        InstanceDetailResponse:
            properties:
                backup_retention_days:
                    minimum: 0.0
                    exclusiveMinimum: true
        InstanceUpdateRequest:
            properties:
                backup_retention_days:
                    minimum: 0.0
                    exclusiveMinimum: true
        InstanceVolumeRequest:
            properties:
                size:
                    example: 30
                type:
                    example: CLOUD_NVME
tags:
-   name: healthcheck
    x-mgc-hidden: true
