# This file is to be merged on top of mgc/cli/openapis/dbaas.openapi.yaml
# using yaml_merge.py
# NOTE: Lists are merged by their indexes, be careful with parameters, tags and such!
# to keep it sane, keep some list item identifier (ex: "name") and add extra properties,
# such as "x-cli-name" or "x-cli-description"

servers:
-   url: https://api-dbaas.{region}.jaxyendy.com
    variables:
        region:
            description: Region to reach the service
            default: br-ne-1
            enum:
            - br-ne-1
            - br-ne-2
            - br-se-1

# ExclusiveMinimum must be replaced from number to boolean. JSON Schema new draft
# proposes as a number, but this is only available in OpenAPI 3.1.0. Since kin-openapi
# only supports up to 3.0.0, we need to patch to be a boolean
components:
    schemas:
        BackupDetailResponse:
            properties:
                db_size:
                    minimum: 0.0
                    exclusiveMinimum: true
                size:
                    minimum: 0.0
                    exclusiveMinimum: true
        InstanceCreateRequest:
            properties:
                backup_retention_days:
                    minimum: 0.0
                    exclusiveMinimum: true
        InstanceDetailResponse:
            properties:
                backup_retention_days:
                    minimum: 0.0
                    exclusiveMinimum: true
        InstanceUpdateRequest:
            properties:
                backup_retention_days:
                    minimum: 0.0
                    exclusiveMinimum: true

tags:
-   name: backups
    description: backups
-   name: datastores
    description: datastores
-   name: flavors
    description: flavors
-   name: instances
    description: instances
-   name: replicas
    description: replicas
