# This file is to be merged on top of mgc/cli/openapis/dbaas.openapi.yaml
# using yaml_merge.py
# NOTE: Lists are merged by their indexes, be careful with parameters, tags and such!
# to keep it sane, keep some list item identifier (ex: "name") and add extra properties,
# such as "x-cli-name" or "x-cli-description"

servers:
-   url: https://api-dbaas{env}.{region}.jaxyendy.com
    variables:
        region:
            description: Region to reach the service
            default: br-ne-1
            enum:
            - br-ne-1
            - br-ne-2
            - br-se-1
        env:
            description: Environment to use
            default: prod
            enum:
            - prod
            - pre-prod
            x-cli-transforms:
            -   type: translate
                translations:
                -   from: prod
                    to: ''
                -   from: pre-prod
                    to: .pre-prod

paths:
    /v1/instances/{instance_id}/backups:
        post:
            responses:
                '202':
                    links:
                        read:
                            operationId: backup_detail_v1_instances__instance_id__backups__backup_id__get
                            description: Read a Backup
                            parameters:
                                instance_id: $request.path.instance_id
                                backup_id: $response.body#/id
                        delete:
                            operationId: delete_backup_v1_instances__instance_id__backups__backup_id__delete
                            description: Delete a Backup
                            parameters:
                                instance_id: $request.path.instance_id
                                backup_id: $response.body#/id
    /v1/instances/{instance_id}/backups/{backup_id}:
        get:
            responses:
                '200':
                    links:
                        delete:
                            operationId: delete_backup_v1_instances__instance_id__backups__backup_id__delete
                            description: Delete a Backup
                            parameters:
                                instance_id: $request.path.instance_id
                                backup_id: request.path.id
    /v1/instances:
        post:
            responses:
              '202':
                  links:
                      read:
                          operationId: instances_v1_get_by_id
                          description: Read Database instance
                          parameters:
                              instance_id: $response.body#/id
                      update:
                          operationId: instances_v1_patch
                          description: Update Database instance
                          parameters:
                              instance_id: $response.body#/id
                      delete:
                          operationId: instances_v1_delete
                          description: Delete Database instance
                          parameters:
                              instance_id: $response.body#/id
    /v1/instances/{instance_id}:
        get:
            responses:
              '200':
                  links:
                      update:
                          operationId: instances_v1_patch
                          description: Update Database instance
                          parameters:
                              instance_id: $request.path.instance_id
                      delete:
                          operationId: instances_v1_delete
                          description: Delete Database instance
                          parameters:
                              instance_id: $request.path.instance_id
        patch:
            responses:
              '200':
                  links:
                      read:
                          operationId: instances_v1_get_by_id
                          description: Read Database instance
                          parameters:
                              instance_id: $request.path.instance_id
                      delete:
                          operationId: instances_v1_delete
                          description: Delete Database instance
                          parameters:
                              instance_id: $request.path.instance_id
    /v1/replicas:
        post:
            responses:
              '202':
                  links:
                      read:
                          operationId: replica_detail_v1_replicas__replica_id__get
                          description: Read Database replica
                          parameters:
                              replica_id: $response.body#/id
                      delete:
                          operationId: replica_delete_v1_replicas__replica_id__delete
                          description: Delete Database replica
                          parameters:
                              replica_id: $response.body#/id
    /v1/replicas/{replica_id}:
        get:
            responses:
              '200':
                  links:
                      delete:
                          operationId: replica_delete_v1_replicas__replica_id__delete
                          description: Delete Database replica
                          parameters:
                              replica_id: $request.path.replica_id

# ExclusiveMinimum must be replaced from number to boolean. JSON Schema new draft
# proposes as a number, but this is only available in OpenAPI 3.1.0. Since kin-openapi
# only supports up to 3.0.0, we need to patch to be a boolean
components:
    schemas:
        BackupDetailResponse:
            properties:
                db_size:
                    minimum: 0.0
                    exclusiveMinimum: true
                size:
                    minimum: 0.0
                    exclusiveMinimum: true
        InstanceCreateRequest:
            properties:
                backup_retention_days:
                    minimum: 0.0
                    exclusiveMinimum: true
        InstanceDetailResponse:
            properties:
                backup_retention_days:
                    minimum: 0.0
                    exclusiveMinimum: true
        InstanceUpdateRequest:
            properties:
                backup_retention_days:
                    minimum: 0.0
                    exclusiveMinimum: true

tags:
-   name: backups
    description: backups
-   name: datastores
    description: datastores
-   name: flavors
    description: flavors
-   name: instances
    description: instances
-   name: replicas
    description: replicas
