# This file is to be merged on top of mgc/cli/openapis/dbaas.openapi.yaml
# using yaml_merge.py
# NOTE: Lists are merged by their indexes, be careful with parameters, tags and such!
# to keep it sane, keep some list item identifier (ex: "name") and add extra properties,
# such as "x-mgc-name" or "x-mgc-description"

paths:
    /v1/instances/{id}/backups:
        post:
            responses:
                '202':
                    links:
                        read:
                            operationId: backup_detail_v1_instances__instance_id__backups__backup_id__get
                            description: Read a Backup
                            parameters:
                                id: $request.path.id
                                backup_id: $response.body#/id
                        delete:
                            operationId: delete_backup_v1_instances__instance_id__backups__backup_id__delete
                            description: Delete a Backup
                            parameters:
                                id: $request.path.id
                                backup_id: $response.body#/id
            security:
                -   OAuth2:
                    - dbaas.write
    /v1/instances/{id}/backups/{backup_id}:
        get:
            responses:
                '200':
                    links:
                        delete:
                            operationId: delete_backup_v1_instances__instance_id__backups__backup_id__delete
                            description: Delete a Backup
                            parameters:
                                id: $request.path.id
                                backup_id: request.path.id
            security:
            -   OAuth2:
                - dbaas.read
        delete:
            security:
            -   OAuth2:
                - dbaas.write
    /v1/datastores:
        get:
            security:
            -   OAuth2:
                - dbaas.read
    /v1/datastores/{datastore_id}:
        get:
            security:
            -   OAuth2:
                - dbaas.read
    /v1/flavors:
        get:
            security:
            -   OAuth2:
                - dbaas.read
    /v1/flavors/{flavor_id}:
        get:
            security:
            -   OAuth2:
                - dbaas.read
    /v1/instances:
        get:
            security:
            -   OAuth2:
                - dbaas.read
        post:
            responses:
              '202':
                  links:
                      read:
                          operationId: instances_v1_get_by_id
                          description: Read Database instance
                          parameters:
                              id: $response.body#/id
                      update:
                          operationId: instances_v1_patch
                          description: Update Database instance
                          parameters:
                              id: $response.body#/id
                      delete:
                          operationId: instances_v1_delete
                          description: Delete Database instance
                          parameters:
                              id: $response.body#/id
            security:
            -   OAuth2:
                - dbaas.write
    /v1/instances/{id}:
        get:
            responses:
              '200':
                  links:
                      update:
                          operationId: instances_v1_patch
                          description: Update Database instance
                          parameters:
                              id: $request.path.id
                      delete:
                          operationId: instances_v1_delete
                          description: Delete Database instance
                          parameters:
                              id: $request.path.id
            security:
            -   OAuth2:
                - dbaas.read
            x-mgc-wait-termination:
                maxRetries: 30
                interval: 10s
                jsonPathQuery: $.result.status == "ACTIVE" || $.result.status == "ERROR"
        delete:
            security:
            -   OAuth2:
                - dbaas.write
        patch:
            responses:
              '200':
                  links:
                      read:
                          operationId: instances_v1_get_by_id
                          description: Read Database instance
                          parameters:
                              id: $request.path.id
                      delete:
                          operationId: instances_v1_delete
                          description: Delete Database instance
                          parameters:
                              id: $request.path.id
            security:
            -   OAuth2:
                - dbaas.write
    /v1/instances/{id}/resize:
        post:
            security:
            -   OAuth2:
                - dbaas.write
    /v1/instances/{id}/start:
        post:
            security:
            -   OAuth2:
                - dbaas.write
    /v1/instances/{id}/stop:
        post:
            security:
            -   OAuth2:
                - dbaas.write
    /v1/replicas:
        get:
            security:
            -   OAuth2:
                - dbaas.read
        post:
            responses:
              '202':
                  links:
                      read:
                          operationId: replica_detail_v1_replicas__replica_id__get
                          description: Read Database replica
                          parameters:
                              replica_id: $response.body#/id
                      delete:
                          operationId: replica_delete_v1_replicas__replica_id__delete
                          description: Delete Database replica
                          parameters:
                              replica_id: $response.body#/id
            security:
                -   OAuth2:
                    - dbaas.write
    /v1/replicas/{replica_id}:
        get:
            responses:
              '200':
                  links:
                      delete:
                          operationId: replica_delete_v1_replicas__replica_id__delete
                          description: Delete Database replica
                          parameters:
                              replica_id: $request.path.replica_id
            security:
            -   OAuth2:
                - dbaas.read
    /v1/replicas/{replica_id}/resize:
        post:
            security:
            -   OAuth2:
                - dbaas.write
    /v1/replicas/{replica_id}/start:
        post:
            security:
            -   OAuth2:
                - dbaas.write
    /v1/replicas/{replica_id}/stop:
        post:
            security:
            -   OAuth2:
                - dbaas.write

servers:
-   url: https://api-dbaas{env}.{region}.jaxyendy.com
    variables:
        region:
            description: Region to reach the service
            default: br-ne-1
            enum:
            - br-ne-1
            - br-ne-2
            - br-se-1
        env:
            description: Environment to use
            default: ''
            enum:
            - ''
            - .pre-prod
            x-mgc-transforms:
            -   type: translate
                translations:
                -   from: prod
                    to: ''
                -   from: pre-prod
                    to: .pre-prod
