# This file is to be merged on top of mgc/cli/openapis/dbaas.openapi.yaml
# using yaml_merge.py
# NOTE: Lists are merged by their indexes, be careful with parameters, tags and such!
# to keep it sane, keep some list item identifier (ex: "name") and add extra properties,
# such as "x-mgc-name" or "x-mgc-description"
servers:
-   url: https://{env}/{region}/database
    variables:
        region:
            description: Region to reach the service
            default: br-se1
            enum:
            - br-ne-1
            - br-se1
            - br-mgl1
            x-mgc-transforms:
            -   type: translate
                allowMissing: true
                translations:
                -   from: br-ne1
                    to: br-ne-1
                -   from: br-mgl1
                    to: br-se-1
        env:
            description: Environment to use
            default: api.magalu.cloud
            enum:
            - api.magalu.cloud
            - api.pre-prod.jaxyendy.com
            x-mgc-transforms:
            -   type: translate
                translations:
                -   from: prod
                    to: api.magalu.cloud
                -   from: pre-prod
                    to: api.pre-prod.jaxyendy.com
# 
# To-do: desbloquear pr #1231, e validar a aplicação desse custom:
# components:
#     schemas:
#         InstanceCreateRequest:
#             title: Instance Create Request
#             required:
#             - name
#             - password
#             - user
#             - volume
#             - engine_id
#             - instance_type_id
#             type: object
#             properties:
#                 name:
#                     title: Name
#                     maxLength: 100
#                     type: string
#                 engine_id:
#                     title: Engine Id
#                     type: string
#                     format: uuid
#                 instance_type_id:
#                     title: Instance Type Id
#                     type: string
#                     format: uuid
#                 user:
#                     title: User
#                     maxLength: 25
#                     type: string
#                 password:
#                     title: Password
#                     maxLength: 50
#                     type: string
#                 volume:
#                     $ref: '#/components/schemas/InstanceVolumeRequest'
#                 parameters:
#                     type: array
#                     items:
#                         $ref: '#/components/schemas/InstanceParametersRequest'
#                     default: []
#                 backup_retention_days:
#                     title: Backup Retention Days
#                     type: integer
#                     default: 7
#                     description: The number of days that a particular backup is kept
#                         until its deletion.
#                 backup_start_at:
#                     title: Backup Start At
#                     description: Start time (UTC timezone) which is allowed to start
#                         the automated backup process.
#                     type: string
#                     format: time
#                     default: 04:00:00