# This file is to be merged on top of mgc/cli/openapis/dbaas.openapi.yaml
# using yaml_merge.py
# NOTE: Lists are merged by their indexes, be careful with parameters, tags and such!
# to keep it sane, keep some list item identifier (ex: "name") and add extra properties,
# such as "x-mgc-name" or "x-mgc-description"

paths:
    /v1/instances/{instance_id}/backups:
        post:
            responses:
                '202':
                    links:
                        read:
                            operationId: backup_detail_v1_instances__instance_id__backups__backup_id__get
                            description: Read a Backup
                            parameters:
                                id: $request.path.id
                                backup_id: $response.body#/id
                        delete:
                            operationId: delete_backup_v1_instances__instance_id__backups__backup_id__delete
                            description: Delete a Backup
                            parameters:
                                id: $request.path.id
                                backup_id: $response.body#/id
            security:
                -   OAuth2:
                    - dbaas.write
    /v1/instances/{instance_id}/backups/{backup_id}:
        get:
            responses:
                '200':
                    links:
                        delete:
                            operationId: delete_backup_v1_instances__instance_id__backups__backup_id__delete
                            description: Delete a Backup
                            parameters:
                                id: $request.path.id
                                backup_id: request.path.id
            security:
            -   OAuth2:
                - dbaas.read
        delete:
            security:
            -   OAuth2:
                - dbaas.write
    /v1/datastores:
        get:
            security:
            -   OAuth2:
                - dbaas.read
    /v1/datastores/{datastore_id}:
        get:
            security:
            -   OAuth2:
                - dbaas.read
    /v1/flavors:
        get:
            security:
            -   OAuth2:
                - dbaas.read
    /v1/flavors/{flavor_id}:
        get:
            security:
            -   OAuth2:
                - dbaas.read
    /v1/instances:
        get:
            security:
            -   OAuth2:
                - dbaas.read
        post:
            responses:
              '202':
                  links:
                      read:
                          operationId: instances_v1_get_by_id
                          description: Read Database instance
                          parameters:
                              id: $response.body#/id
                      update:
                          operationId: instances_v1_patch
                          description: Update Database instance
                          parameters:
                              id: $response.body#/id
                      delete:
                          operationId: instances_v1_delete
                          description: Delete Database instance
                          parameters:
                              id: $response.body#/id
            security:
            -   OAuth2:
                - dbaas.write
    /v1/instances/{instance_id}:
        get:
            responses:
              '200':
                  links:
                      update:
                          operationId: instances_v1_patch
                          description: Update Database instance
                          parameters:
                              id: $request.path.id
                      delete:
                          operationId: instances_v1_delete
                          description: Delete Database instance
                          parameters:
                              id: $request.path.id
                      update/flavor_id:
                          operationId: instances_v1_resize
                          description: Resizes a database instance.
                          parameters:
                              id: $request.path.id
                          x-mgc-hidden: true
                      update/volume:
                          operationId: instances_v1_resize
                          description: Resizes a database instance.
                          parameters:
                              id: $request.path.id
                          x-mgc-hidden: true
                      update/status/ACTIVE:
                          operationId: instances_v1_start
                          description: Starts a database instance.
                          parameters:
                              id: $request.path.id
                          x-mgc-hidden: true
                      update/status/STOPPED:
                          operationId: instances_v1_stop
                          description: Stops a database instance.
                          parameters:
                              id: $request.path.id
                          x-mgc-hidden: true
            security:
            -   OAuth2:
                - dbaas.read
            x-mgc-wait-termination:
                maxRetries: 100
                interval: 20s
                jsonPathQuery: $.result.status != "CREATING"
        delete:
            security:
            -   OAuth2:
                - dbaas.write
        patch:
            responses:
              '200':
                  links:
                      read:
                          operationId: instances_v1_get_by_id
                          description: Read Database instance
                          parameters:
                              id: $request.path.id
                          x-mgc-wait-termination:
                              maxRetries: 20
                              interval: 10s
                              jsonPathQuery: ($.owner.parameters.status != null && $.result.status == $.owner.parameters.status) || $.result.status != "CREATING"
                      delete:
                          operationId: instances_v1_delete
                          description: Delete Database instance
                          parameters:
                              id: $request.path.id
            security:
            -   OAuth2:
                - dbaas.write
    /v1/instances/{instance_id}/resize:
        post:
            security:
            -   OAuth2:
                - dbaas.write
    /v1/instances/{instance_id}/start:
        post:
            responses:
              '200':
                  links:
                      read:
                          operationId: instances_v1_get_by_id
                          description: Read Database instance
                          parameters:
                              id: $request.path.id
                          x-mgc-wait-termination:
                              maxRetries: 20
                              interval: 10s
                              jsonPathQuery: $.result.status == "ACTIVE"
            security:
            -   OAuth2:
                - dbaas.write
    /v1/instances/{instance_id}/stop:
        post:
            responses:
              '200':
                  links:
                      read:
                          operationId: instances_v1_get_by_id
                          description: Read Database instance
                          parameters:
                              id: $request.path.id
                          x-mgc-wait-termination:
                              maxRetries: 20
                              interval: 10s
                              jsonPathQuery: $.result.status == "STOPPED"
            security:
            -   OAuth2:
                - dbaas.write
    /v1/replicas:
        get:
            security:
            -   OAuth2:
                - dbaas.read
        post:
            responses:
              '202':
                  links:
                      read:
                          operationId: replica_detail_v1_replicas__replica_id__get
                          description: Read Database replica
                          parameters:
                              replica_id: $response.body#/id
                      delete:
                          operationId: replica_v1_delete
                          description: Delete Database replica
                          parameters:
                              replica_id: $response.body#/id
            security:
                -   OAuth2:
                    - dbaas.write
    /v1/replicas/{replica_id}:
        get:
            responses:
              '200':
                  links:
                      delete:
                          operationId: replica_v1_delete
                          description: Delete Database replica
                          parameters:
                              replica_id: $request.path.replica_id
                      update/flavor_id:
                          operationId: replica_resize_v1_replicas_post
                          description: Replica Resize.
                          parameters:
                              replica_id: $request.path.replica_id
                      update/status/ACTIVE:
                          operationId: replica_start_v1_replicas__replica_id__start_post
                          description: Start an instance replica.
                          parameters:
                              id: $request.path.id
                          x-mgc-hidden: true
                      update/status/STOPPED:
                          operationId: replica_stop_v1_replicas__replica_id__stop_post
                          description: Stop an instance replica.
                          parameters:
                              id: $request.path.id
                          x-mgc-hidden: true
            security:
            -   OAuth2:
                - dbaas.read
    /v1/replicas/{replica_id}/resize:
        post:
            security:
            -   OAuth2:
                - dbaas.write
    /v1/replicas/{replica_id}/start:
        post:
            security:
            -   OAuth2:
                - dbaas.write
    /v1/replicas/{replica_id}/stop:
        post:
            security:
            -   OAuth2:
                - dbaas.write

tags:
-   name: healthcheck
    x-mgc-hidden: true
-   name: backups
-   name: datastores
-   name: instances
-   name: flavors
-   name: replicas
-   name: restores
    x-mgc-hidden: true

servers:
-   url: https://{env}/{region}/database
    variables:
        region:
            description: Region to reach the service
            default: br-ne-1
            enum:
            - br-ne-1
            - br-se-1
        env:
            description: Environment to use
            default: api2.magalu.cloud
            enum:
            - api2.magalu.cloud
            - api.pre-prod.jaxyendy.com
            x-mgc-transforms:
            -   type: translate
                translations:
                -   from: prod
                    to: api2.magalu.cloud
                -   from: pre-prod
                    to: api.pre-prod.jaxyendy.com
