# This file is to be merged on top of mgc/cli/openapis/mke.openapi.yaml
# using yaml_merge.py
# NOTE: Lists are merged by their indexes, be careful with parameters, tags and such!
# to keep it sane, keep some list item identifier (ex: "name") and add extra properties,
# such as "x-mgc-name" or "x-mgc-description"

servers:
-   url: https://{env}/{region}/kubernetes
    variables:
        region:
            description: Region to reach the service
            default: br-ne-1
            enum:
            - br-ne-1
            - br-se-1
            x-mgc-transforms:
            -   type: translate
                translations:
                -   from: br-ne1
                    to: br-ne-1
                -   from: br-se1
                    to: br-se-1
        env:
            description: Environment to use
            default: api.magalu.cloud
            enum:
            - api.magalu.cloud
            - api.pre-prod.jaxyendy.com
            x-mgc-transforms:
            -   type: translate
                translations:
                -   from: prod
                    to: api.magalu.cloud
                -   from: pre-prod
                    to: api.pre-prod.jaxyendy.com

paths:
    /v0/clusters:
        post:
            responses:
                '201':
                    links:
                        get:
                            operationId: getClusterById
                            description: Lista as informações de um cluster
                            parameters:
                                id: $response.body#/id
                        delete:
                            operationId: deleteCluster
                            description: Deleta um cluster
                            parameters:
                                id: $response.body#/id
    /v0/clusters/{cluster_id}:
        get:
            parameters:
            -   name: cluster_id
                x-mgc-name: id
            responses:
                '200':
                    links:
                        delete:
                            operationId: deleteCluster
                            description: Deleta um cluster
                            parameters:
                                cluster_id: $request.path.cluster_id
        delete:
            parameters:
            -   name: cluster_id
                x-mgc-name: id
    /v0/clusters/{cluster_id}/kubeconfig:
        get:
            parameters:
            -   name: cluster_id
                x-mgc-name: id
    /v0/clusters/{cluster_id}/node_pools:
        post:
            responses:
                '201':
                    links:
                        get:
                            operationId: getNodePool
                            description: Lista nodes de um node pool
                            parameters:
                                cluster_id: $request.path.cluster_id
                                node_pool_id: $response.body#/id
                        update:
                            operationId: patchNodePool
                            description: Atualiza nodes de um node pool
                            parameters:
                                cluster_id: $request.path.cluster_id
                                node_pool_id: $response.body#/id
                        delete:
                            operationId: deleteNodePool
                            description: Deleta um node pool em um cluster do Kubernetes
                            parameters:
                                cluster_id: $request.path.cluster_id
                                node_pool_id: $response.body#/id
    /v0/clusters/{cluster_id}/node_pools/{node_pool_id}:
        get:
            parameters:
            -   name: cluster_id
            -   name: node_pool_id
                x-mgc-name: id
            responses:
                '200':
                    links:
                        update:
                            operationId: patchNodePool
                            description: Atualiza nodes de um node pool
                            parameters:
                                cluster_id: $request.path.cluster_id
                                node_pool_id: $request.path.node_pool_id
                        delete:
                            operationId: deleteNodePool
                            description: Deleta um node pool em um cluster do Kubernetes
                            parameters:
                                cluster_id: $request.path.cluster_id
                                node_pool_id: $request.path.node_pool_id
        patch:
            parameters:
            -   name: cluster_id
            -   name: node_pool_id
                x-mgc-name: id
            responses:
                '200':
                    links:
                        get:
                            operationId: getNodePool
                            description: Lista nodes de um node pool
                            parameters:
                                cluster_id: $request.path.cluster_id
                                node_pool_id: $request.path.node_pool_id
                        delete:
                            operationId: deleteNodePool
                            description: Deleta um node pool em um cluster do Kubernetes
                            parameters:
                                cluster_id: $request.path.cluster_id
                                node_pool_id: $request.path.node_pool_id
        delete:
            parameters:
            -   name: cluster_id
            -   name: node_pool_id
                x-mgc-name: id
