# This file is to be merged on top of mgc/cli/openapis/mke.openapi.yaml
# using yaml_merge.py
# NOTE: Lists are merged by their indexes, be careful with parameters, tags and such!
# to keep it sane, keep some list item identifier (ex: "name") and add extra properties,
# such as "x-mgc-name" or "x-mgc-description"

servers:
-   url: https://api-mke{env}.{region}.jaxyendy.com
    variables:
        region:
            description: Region to reach the service
            default: br-ne-1
            enum:
            - br-ne-1
            - br-ne-2
            - br-se-1
        env:
            description: Environment to use
            default: ''
            enum:
            - ''
            - .pre-prod
            x-mgc-transforms:
            -   type: translate
                translations:
                -   from: prod
                    to: ''
                -   from: pre-prod
                    to: .pre-prod

path:
    /v0/clusters:
        post:
            responses:
                '201':
                    links:
                        read:
                            operationId: getClusterById
                            description: Read cluster
                            parameters:
                                - custer_id: $response.body#/id
                        delete:
                            operationId: deleteCluster
                            description: Delete cluster
                            parameters:
                                - custer_id: $response.body#/id
    /v0/clusters/{cluster_id}:
        get:
            responses:
                '200':
                    links:
                        delete:
                            operationId: deleteCluster
                            description: Delete cluster
                            parameters:
                                - custer_id: $request.path.id
    /v0/clusters/{cluster_id}/node_pools:
        post:
            responses:
                '201':
                    links:
                        read:
                            operationId: getNodePool
                            description: Read node pool
                            parameters:
                                - cluster_id: $request.path.cluster_id
                                - node_pool_id: $response.body#/id
                        update:
                            operationId: patchNodePool
                            description: Read node pool
                            parameters:
                                - cluster_id: $request.path.cluster_id
                                - node_pool_id: $response.body#/id
                        delete:
                            operationId: deleteNodePool
                            description: Delete node pool
                            parameters:
                                - cluster_id: $request.path.cluster_id
                                - node_pool_id: $response.body#/id
    /v0/clusters/{cluster_id}/node_pools/{node_pool_id}:
        get:
            responses:
                '200':
                    links:
                        update:
                            operationId: patchNodePool
                            description: Read node pool
                            parameters:
                                - cluster_id: $request.path.cluster_id
                                - node_pool_id: $request.path.node_pool_id
                        delete:
                            operationId: deleteNodePool
                            description: Delete node pool
                            parameters:
                                - cluster_id: $request.path.cluster_id
                                - node_pool_id: $request.path.node_pool_id
        post:
            responses:
                '200':
                    links:
                        read:
                            operationId: getNodePool
                            description: Read node pool
                            parameters:
                                - cluster_id: $request.path.cluster_id
                                - node_pool_id: $request.path.node_pool_id
                        delete:
                            operationId: deleteNodePool
                            description: Delete node pool
                            parameters:
                                - cluster_id: $request.path.cluster_id
                                - node_pool_id: $request.path.node_pool_id
