# This file is to be merged on top of mgc/cli/openapis/vpc.openapi.yaml
# using yaml_merge.py
# NOTE: Lists are merged by their indexes, be careful with parameters, tags and such!
# to keep it sane, keep some list item identifier (ex: "name") and add extra properties,
# such as "x-mgc-name" or "x-mgc-description"

servers:
-   url: https://{env}/{region}/network
    variables:
        region:
            description: Region to reach the service
            default: br-ne-1
            enum:
            - br-ne-1
            - br-se1
            - br-mgl1
            x-mgc-transforms:
            -   type: translate
                allowMissing: true
                translations:
                -   from: br-ne1
                    to: br-ne-1
                -   from: br-mgl1
                    to: br-se-1
        env:
            description: Environment to use
            default: api.magalu.cloud
            enum:
            - api.magalu.cloud
            - api.pre-prod.jaxyendy.com
            x-mgc-transforms:
            -   type: translate
                translations:
                -   from: prod
                    to: api.magalu.cloud
                -   from: pre-prod
                    to: api.pre-prod.jaxyendy.com

paths:
  /v0/vpcs/{vpc_id}/ports:
    get:
      tags:
        - vpc
      x-mgc-description: List VPC ports
    post:
      tags:
        - vpc
  /v0/vpcs/{vpc_id}/public_ips:
    post:
      tags:
        - vpc
      x-mgc-hidden: true
    get:
      tags:
        - vpc
  /v0/vpcs/{vpc_id}/security_groups:
    post:
      tags:
        - vpc
    get:
      tags:
        - vpc
  /v0/security_groups/{security_group_id}/rules:
    post:
      tags:
        - security_group
      x-mgc-hidden: true
    get:
      tags:
        - security_group
      x-mgc-hidden: true
  /v0/rules/{rule_id}:
    get:
      responses:
        '200':
          links:
            delete:
              operationId: deleteRule
              description: Delete Rule
              parameters:
                rule_id: $request.path.rule_id
  /v0/ports:
    post:
      x-mgc-name: create-default-vpc
#   The following links are for creating a Terraform Connection Resource automatically.
#   Unfortunately, the ConnectionResources have a bug because Terraform is losing
#   private state between requests (bug in Terraform). When that is resolved, this
#   may be uncommented and the Blueprint version of this (volume-attachment) won't be needed anymor
#   /v0/ports/{port_id}/attach/{security_group_id}:
#     post:
#       responses:
#         '200':
#           links:
#             get-connection: # Connection resources
#               description: Check if a Security Group is attached to this Port
#               operationId: portDetails
#               parameters:
#                   port_id: $request.path.port_id
#               x-mgc-wait-termination:
#                   maxRetries: 2
#                   interval: 5s
#                   jsonPathQuery: $.result.security_groups[?(@ == $.owner.parameters.security_group_id)]
#             delete-connection:
#                 description: Detach this Security Group from this Port
#                 operationId: detachSecurityGroup
#                 parameters:
#                     port_id: $request.path.port_id
#                     security_group_id: $request.path.security_group_id
#   /v0/public_ips/{public_ip_id}/attach/{port_id}:
#     post:
#       responses:
#         '200':
#           links:
#             get-connection: # Connection Resource
#               description: Check if this Public IP is attached to this Port
#               operationId: publicIpDetails
#               parameters:
#                 public_ip_id: $request.path.public_ip_id
#                 port_id: $request.path.port_id
#               x-mgc-wait-termination:
#                 maxRetries: 2
#                 interval: 5s
#                 jsonPathQuery: hasKey($.result, "port_id") && $.result.port_id == $.owner.parameters.port_id
#             delete-connection:
#                 description: Detach this Public IP from this Port
#                 operationId: detachPublicIp
#                 parameters:
#                   public_ip_id: $request.path.public_ip_id
#                   port_id: $request.path.port_id
  /v0/vpcs/{vpc_id}/subnets:
    get:
      x-mgc-hidden: true
    post:
      x-mgc-hidden: true

tags:
-   name: healthcheck
    x-mgc-hidden: true
-   name: port
    x-mgc-name: ports
    x-mgc-description: VPC Port
-   name: public_ip
    x-mgc-name: public_ips
    x-mgc-description: VPC Public IPs
-   name: quotas
    x-mgc-description: VPC Quotas
    x-mgc-hidden: true
-   name: rule
    x-mgc-name: rules
    x-mgc-description: VPC Rules
-   name: security_group
    x-mgc-name: security_groups
    x-mgc-description: VPC Security Groups
-   name: subnets
    x-mgc-description: VPC Subnets
-   name: vpc
    x-mgc-name: vpcs
    x-mgc-description: Virtual Private Cloud (VPC)
-   name: worker_public_ips
    x-mgc-hidden: true
