# This file is to be merged on top of mgc/cli/openapis/vpc.openapi.yaml
# using yaml_merge.py
# NOTE: Lists are merged by their indexes, be careful with parameters, tags and such!
# to keep it sane, keep some list item identifier (ex: "name") and add extra properties,
# such as "x-mgc-name" or "x-mgc-description"

servers:
-   url: https://{env}/{region}/network
    variables:
        region:
            description: Region to reach the service
            default: br-se1
            enum:
            - br-ne-1
            - br-se1
            - br-mgl1
            x-mgc-transforms:
            -   type: translate
                allowMissing: true
                translations:
                -   from: br-ne1
                    to: br-ne-1
                -   from: br-mgl1
                    to: br-se-1
        env:
            description: Environment to use
            default: api.magalu.cloud
            enum:
            - api.magalu.cloud
            - api.pre-prod.jaxyendy.com
            x-mgc-transforms:
            -   type: translate
                translations:
                -   from: prod
                    to: api.magalu.cloud
                -   from: pre-prod
                    to: api.pre-prod.jaxyendy.com
tags:
-   name: healthcheck
    description: healthcheck
    x-mgc-hidden: true
-   name: interconnections
    description: interconnections
    x-mgc-hidden: true
-   name: internal
    description: internal
    x-mgc-hidden: true
-   name: port
    description: port
    x-mgc-name: ports
    x-mgc-description: 'VPC Port'
-   name: public_ip
    description: public_ip
    x-mgc-name: public_ips
    x-mgc-description: 'VPC Public IPs'
-   name: quotas
    description: quotas
    x-mgc-hidden: true
-   name: rule
    description: rule
    x-mgc-name: rules
    x-mgc-description: 'VPC Rules'
-   name: security_group
    x-mgc-name: security_groups
    description: security_group
    x-mgc-description: 'VPC Security Groups'
-   name: subnetpools
    description: subnetpools
    x-mgc-hidden: true
-   name: subnets
    description: subnets
    x-mgc-description: 'VPC Subnets'
-   name: vpc
    description: vpc
    x-mgc-name: vpcs
    x-mgc-description: 'Virtual Private Cloud (VPC)'
-   name: worker_public_ips
    description: worker_public_ips
    x-mgc-hidden: true
