# This file is to be merged on top of mgc/cli/openapis/object-storage.openapi.yaml
# using yaml_merge.py
# NOTE: Lists are merged by their indexes, be careful with parameters, tags and such!
# to keep it sane, keep some list item identifier (ex: "name") and add extra properties,
# such as "x-mgc-name" or "x-mgc-description"

servers:
-   url: https://api-object-storage{env}.{region}.jaxyendy.com
    variables:
        region:
            description: Region to reach the service
            default: br-ne-1
            enum:
            - br-ne-1
            - br-ne-2
            - br-se-1
        env:
            description: Environment to use
            default: ''
            enum:
            - ''
            - .pre-prod
            x-mgc-transforms:
            -   type: translate
                translations:
                -   from: prod
                    to: ''
                -   from: pre-prod
                    to: .pre-prod

paths:
    /v1/storage/b/{bucket_name}:
        get:
            parameters:
            -   description: Nome do bucket
                required: true
                schema:
                    title: Bucket Name
                    type: string
                    description: Nome do bucket
                name: bucket_name
                in: path
            -   description: Indica se o nome do bucket informado deve ser utilizado
                    como uma busca exata ou por prefixo
                required: false
                schema:
                    title: Prefix
                    type: boolean
                    description: Indica se o nome do bucket informado deve ser utilizado
                        como uma busca exata ou por prefixo
                    default: false
                name: prefix
                in: query
            -   required: false
                schema:
                    title: Limit
                    exclusiveMinimum: true
                    minimum: 0.0
                    type: integer
                name: limit
                in: query
            -   required: false
                schema:
                    title: Offset
                    type: string
                name: offset
                in: query
    /v1/storage/b:
        get:
            parameters:
            -   required: false
                schema:
                    title: Limit
                    minimum: 0.0
                    exclusiveMinimum: true
                    type: integer
                name: limit
                in: query
            -   required: false
                schema:
                    title: Offset
                    type: string
                name: offset
                in: query
    /v2/buckets/{bucket_name}:
        get:
            parameters:
            -   description: Nome do bucket
                required: true
                schema:
                    title: Bucket Name
                    type: string
                    description: Nome do bucket
                name: bucket_name
                in: path
            -   description: Indica se o nome do bucket informado deve ser utilizado
                    como uma busca exata ou por prefixo
                required: false
                schema:
                    title: Prefix
                    type: boolean
                    description: Indica se o nome do bucket informado deve ser utilizado
                        como uma busca exata ou por prefixo
                    default: false
                name: prefix
                in: query
            -   required: false
                schema:
                    title: ' Limit'
                    minimum: 0.0
                    exclusiveMinimum: true
                    type: integer
                name: _limit
                in: query
            -   required: false
                schema:
                    title: ' Marker'
                    type: string
                name: _marker
                in: query
            -   required: false
                schema:
                    title: ' Reverse'
                    type: boolean
                    default: false
                name: _reverse
                in: query
    /v2/buckets:
        get:
            parameters:
            -   required: false
                schema:
                    title: ' Limit'
                    minimum: 0.0
                    exclusiveMinimum: true
                    type: integer
                    default: 10
                name: _limit
                in: query
            -   required: false
                schema:
                    title: ' Marker'
                    type: string
                name: _marker
                in: query
            -   required: false
                schema:
                    title: ' Reverse'
                    type: boolean
                    default: false
                name: _reverse
                in: query
    /v1/storage/m/{bucket_name}:
        get:
            parameters:
            -   description: Nome do bucket
                required: true
                schema:
                    title: Bucket Name
                    type: string
                    description: Nome do bucket
                name: bucket_name
                in: path
            -   description: Busca por prefixo do arquivo se oject_file n達o for informado
                required: false
                schema:
                    title: Prefix
                    type: string
                    description: Busca por prefixo do arquivo se oject_file n達o for
                        informado
                name: prefix
                in: query
            -   required: false
                schema:
                    title: Limit
                    minimum: 0.0
                    exclusiveMinimum: true
                    type: integer
                name: limit
                in: query
            -   required: false
                schema:
                    title: Offset
                    type: string
                name: offset
                in: query
    /v2/metadata/{bucket_name}:
        get:
            parameters:
            -   description: Nome do bucket
                required: true
                schema:
                    title: Bucket Name
                    type: string
                    description: Nome do bucket
                name: bucket_name
                in: path
            -   description: Busca por prefixo do arquivo se oject_file n達o for informado
                required: false
                schema:
                    title: Prefix
                    type: string
                    description: Busca por prefixo do arquivo se oject_file n達o for
                        informado
                name: prefix
                in: query
            -   required: false
                schema:
                    title: ' Limit'
                    minimum: 0.0
                    exclusiveMinimum: true
                    type: integer
                name: _limit
                in: query
            -   required: false
                schema:
                    title: ' Marker'
                    type: string
                name: _marker
                in: query
            -   required: false
                schema:
                    title: ' Reverse'
                    type: boolean
                    default: false
                name: _reverse
                in: query
    /v1/storage/xaas/b/{bucket_name}:
        get:
            parameters:
            -   description: Nome do bucket
                required: true
                schema:
                    title: Bucket Name
                    type: string
                    description: Nome do bucket
                name: bucket_name
                in: path
            -   required: true
                schema:
                    $ref: '#/components/schemas/ProjectType'
                name: project_type
                in: query
            -   description: Indica se o nome do bucket informado deve ser utilizado
                    como uma busca exata ou por prefixo
                required: false
                schema:
                    title: Prefix
                    type: boolean
                    description: Indica se o nome do bucket informado deve ser utilizado
                        como uma busca exata ou por prefixo
                    default: false
                name: prefix
                in: query
            -   required: false
                schema:
                    title: Limit
                    minimum: 0.0
                    exclusiveMinimum: true
                    type: integer
                name: limit
                in: query
            -   required: false
                schema:
                    title: Offset
                    type: string
                name: offset
                in: query
    /v1/storage/xaas/b:
        get:
            parameters:
            -   required: true
                schema:
                    $ref: '#/components/schemas/ProjectType'
                name: project_type
                in: query
            -   required: false
                schema:
                    title: Limit
                    minimum: 0.0
                    exclusiveMinimum: true
                    type: integer
                name: limit
                in: query
            -   required: false
                schema:
                    title: Offset
                    type: string
                name: offset
                in: query
    /v2/xaas/buckets/{bucket_name}:
        get:
            parameters:
            -   description: Nome do bucket
                required: true
                schema:
                    title: Bucket Name
                    type: string
                    description: Nome do bucket
                name: bucket_name
                in: path
            -   required: true
                schema:
                    $ref: '#/components/schemas/ProjectType'
                name: project_type
                in: query
            -   description: Indica se o nome do bucket informado deve ser utilizado
                    como uma busca exata ou por prefixo
                required: false
                schema:
                    title: Prefix
                    type: boolean
                    description: Indica se o nome do bucket informado deve ser utilizado
                        como uma busca exata ou por prefixo
                    default: false
                name: prefix
                in: query
            -   required: false
                schema:
                    title: ' Limit'
                    minimum: 0.0
                    exclusiveMinimum: true
                    type: integer
                name: _limit
                in: query
            -   required: false
                schema:
                    title: ' Marker'
                    type: string
                name: _marker
                in: query
            -   required: false
                schema:
                    title: ' Reverse'
                    type: boolean
                    default: false
                name: _reverse
                in: query
    /v2/xaas/buckets:
        get:
            parameters:
            -   required: true
                schema:
                    $ref: '#/components/schemas/ProjectType'
                name: project_type
                in: query
            -   required: false
                schema:
                    title: ' Limit'
                    minimum: 0.0
                    exclusiveMinimum: true
                    type: integer
                    default: 10
                name: _limit
                in: query
            -   required: false
                schema:
                    title: ' Marker'
                    type: string
                name: _marker
                in: query
            -   required: false
                schema:
                    title: ' Reverse'
                    type: boolean
                    default: false
                name: _reverse
                in: query
    /v1/storage/xaas/m/{bucket_name}:
        get:
            parameters:
            -   description: Nome do bucket
                required: true
                schema:
                    title: Bucket Name
                    type: string
                    description: Nome do bucket
                name: bucket_name
                in: path
            -   required: true
                schema:
                    $ref: '#/components/schemas/ProjectType'
                name: project_type
                in: query
            -   description: Busca por prefixo do arquivo se oject_file n達o for informado
                required: false
                schema:
                    title: Prefix
                    type: string
                    description: Busca por prefixo do arquivo se oject_file n達o for
                        informado
                name: prefix
                in: query
            -   required: false
                schema:
                    title: Limit
                    minimum: 0.0
                    exclusiveMinimum: true
                    type: integer
                name: limit
                in: query
            -   required: false
                schema:
                    title: Offset
                    type: string
                name: offset
                in: query
    /v2/xaas/metadata/{bucket_name}:
        get:
            parameters:
            -   description: Nome do bucket
                required: true
                schema:
                    title: Bucket Name
                    type: string
                    description: Nome do bucket
                name: bucket_name
                in: path
            -   required: true
                schema:
                    $ref: '#/components/schemas/ProjectType'
                name: project_type
                in: query
            -   description: Busca por prefixo do arquivo se oject_file n達o for informado
                required: false
                schema:
                    title: Prefix
                    type: string
                    description: Busca por prefixo do arquivo se oject_file n達o for
                        informado
                name: prefix
                in: query
            -   required: false
                schema:
                    title: ' Limit'
                    minimum: 0.0
                    exclusiveMinimum: true
                    type: integer
                name: _limit
                in: query
            -   required: false
                schema:
                    title: ' Marker'
                    type: string
                name: _marker
                in: query
            -   required: false
                schema:
                    title: ' Reverse'
                    type: boolean
                    default: false
                name: _reverse
                in: query
    /v1/buckets:
        get:
            tags:
            - bucket
            summary: Get All Buckets
            description: Lista paginada de todos buckets que o usu叩rio possui permiss達o
            operationId: get_all_buckets_v1_buckets_get
            parameters:
            -   required: false
                schema:
                    title: Limit
                    minimum: 0.0
                    exclusiveMinimum: true
                    type: integer
                name: limit
                in: query
            -   required: false
                schema:
                    title: Offset
                    type: string
                name: offset
                in: query
