openapi: 3.0.3
paths:
    /v0/ssh-keys:
        get:
            parameters:
            -   name: _limit
                in: query
                schema:
                    type: integer
                    default: 50
            -   name: _offset
                in: query
                schema:
                    type: integer
                    default: 0
            -   name: _sort
                in: query
                schema:
                    default: name:asc