# This file is to be merged on top of mgc/cli/openapis/profile.openapi.yaml
# using yaml_merge.py
# NOTE: Lists are merged by their indexes, be careful with parameters, tags and such!
# to keep it sane, keep some list item identifier (ex: "name") and add extra properties,
# such as "x-mgc-name" or "x-mgc-description"

servers:
-   url: https://{env}/profile
    variables:
        env:
            description: Environment to use
            default: api.magalu.cloud
            enum:
            - api.magalu.cloud
            - api.pre-prod.jaxyendy.com
            x-mgc-transforms:
            -   type: translate
                translations:
                -   from: prod
                    to: api.magalu.cloud
                -   from: pre-prod
                    to: api.pre-prod.jaxyendy.com
paths:
    /v0/ssh-keys:
        get:
            tags:
            - ssh_keys
            x-mgc-output-flag: remove=$.results[*].key
tags:
-   name: ssh_keys
    description: ssh_keys
    x-mgc-description: Manage SSH Keys