# This file is to be merged on top of mgc/cli/openapis/vpc.openapi.yaml
# using yaml_merge.py
# NOTE: Lists are merged by their indexes, be careful with parameters, tags and such!
# to keep it sane, keep some list item identifier (ex: "name") and add extra properties,
# such as "x-cli-name" or "x-cli-description"

servers:
-   url: https://api-virtual-machine{env}.{region}.jaxyendy.com
    variables:
        region:
            description: Region to reach the service
            default: br-ne-1
            enum:
            - br-ne-1
            - br-ne-2
            - br-se-1
        env:
            description: Environment to use
            default: prod
            enum:
            - prod
            - pre-prod
            x-cli-transforms:
            -   type: translate
                translations:
                -   from: prod
                    to: ''
                -   from: pre-prod
                    to: .pre-prod

paths:
    /v0/instances:
        get:
            x-cli-description: List Virtual Machine instances
            x-cli-output-flag: table=NAME:$.instances[*].name,ID:$.instances[*].id
        post:
            x-cli-description: Create a Virtual Machine instance
            responses:
                '200':
                    links:
                        read:
                            description: Read Virtual Machine instance
                            operationId: instance_details_v0_instances__id__get
                            parameters:
                                id: $response.body#/id
                        update:
                            description: Update Virtual Machine instance
                            operationId: update_instance_status_v0_instances__id__patch
                            parameters:
                                id: $response.body#/id
                        delete:
                            description: Delete Virtual Machine instance
                            operationId: instance_delete_v0_instances__id__delete
                            parameters:
                                id: $response.body#/id
    /v0/instances/{id}:
        get:
            x-cli-description: Get a Virtual Machine instance details
            x-cli-wait-termination:
                maxRetries: 30
                intervalInSeconds: 1s
                jsonPathQuery: "$.status == \"active\" || $.status == \"shutoff\" || $.status == \"error\""
            responses:
                '200':
                    links:
                        update:
                            description: Update Virtual Machine instance
                            operationId: update_instance_status_v0_instances__id__patch
                            parameters:
                                id: $request.path.id
                        delete:
                            description: Delete Virtual Machine instance
                            operationId: instance_delete_v0_instances__id__delete
                            parameters:
                                id: $request.path.id
        delete:
            x-cli-description: Delete a Virtual Machine instance
        patch:
            x-cli-description: Update a Virtual Machine instance
            responses:
                '200':
                    links:
                        read:
                            description: Read Virtual Machine instance
                            operationId: instance_details_v0_instances__id__get
                            parameters:
                                id: $request.path.id
                        delete:
                            description: Delete Virtual Machine instance
                            operationId: instance_delete_v0_instances__id__delete
                            parameters:
                                id: $request.path.id
/v0/images:
    post:
        responses:
            '201':
                links:
                    delete:
                        operationId: delete_image_v0_images__image_id__delete
                        description: Delete image in DB
                        parameters:
                            image_id: $response.body#/id
/v0/instance_types:
    post:
        responses:
            '201':
                links:
                    delete:
                        operationId: delete_instance_type_v0_instance_types__instance_type_id__delete
                        description: Delete Instance Type
                        parameters:
                            instance_type_id: $response.body#/id
/v0/keypairs:
    post:
        responses:
            '201':
                links:
                    delete:
                        operationId: delete_keypair_v0_keypairs__keypair_name__delete
                        description: Delete keypair
                        parameters:
                            keypair_name: $response.body#/name
/v0/keypairs/{keypair_name}:
    post:
        responses:
            '201':
                links:
                    delete:
                        operationId: delete_keypair_v0_keypairs__keypair_name__delete
                        description: Delete keypair
                        parameters:
                            keypair_name: $response.body#/name

components:
    schemas:
        InstanceResponse:
            properties:
                status:
                    x-cli-transforms:
                    -   type: lowercase

tags:
-   name: instances
    description: instances
-   name: healthchecks
    description: healthchecks
    x-cli-hidden: true
-   name: keypairs
    description: keypairs
-   name: instance-types
    description: instance types
-   name: images
    description: images
-   name: usage
    description: usage
