# This file is to be merged on top of mgc/cli/openapis/vpc.openapi.yaml
# using yaml_merge.py
# NOTE: Lists are merged by their indexes, be careful with parameters, tags and such!
# to keep it sane, keep some list item identifier (ex: "name") and add extra properties,
# such as "x-mgc-name" or "x-mgc-description"

paths:
    /v0/instances:
        get:
            x-mgc-description: List Virtual Machine instances
            x-mgc-output-flag: table=NAME:$.instances[*].name,ID:$.instances[*].id
        post:
            x-mgc-description: Create a Virtual Machine instance
            responses:
                '200':
                    links:
                        read:
                            description: Read Virtual Machine instance
                            operationId: instance_details_v0_instances__id__get
                            parameters:
                                id: $response.body#/id
                        update:
                            description: Update Virtual Machine instance
                            operationId: update_instance_status_v0_instances__id__patch
                            parameters:
                                id: $response.body#/id
                        delete:
                            description: Delete Virtual Machine instance
                            operationId: instance_delete_v0_instances__id__delete
                            parameters:
                                id: $response.body#/id
    /v0/instances/{id}:
        get:
            x-mgc-description: Get a Virtual Machine instance details
            x-mgc-wait-termination:
                maxRetries: 30
                interval: 1s
                jsonPathQuery: $.result.status == "active" || $.result.status == "shutoff" || $.result.status == "error"
            responses:
                '200':
                    links:
                        update:
                            description: Update Virtual Machine instance
                            operationId: update_instance_status_v0_instances__id__patch
                            parameters:
                                id: $request.path.id
                        delete:
                            description: Delete Virtual Machine instance
                            operationId: instance_delete_v0_instances__id__delete
                            parameters:
                                id: $request.path.id
        delete:
            x-mgc-description: Delete a Virtual Machine instance
        patch:
            x-mgc-description: Update a Virtual Machine instance
            responses:
                '204':
                    links:
                        read:
                            description: Read Virtual Machine instance
                            operationId: instance_details_v0_instances__id__get
                            parameters:
                                id: $request.path.id
                            x-mgc-wait-termination:
                                maxRetries: 4
                                interval: 5s
                                jsonPathQuery: $.result.status == $.owner.parameters.status
                        delete:
                            description: Delete Virtual Machine instance
                            operationId: instance_delete_v0_instances__id__delete
                            parameters:
                                id: $request.path.id
    /v0/images:
        post:
            responses:
                '201':
                    links:
                        delete:
                            operationId: delete_image_v0_images__image_id__delete
                            description: Delete image in DB
                            parameters:
                                image_id: $response.body#/id
    /v0/images/{image_id}:
        delete:
            parameters:
            -   name: image_id
                x-mgc-name: id
    /v0/instance_types:
        post:
            x-mgc-hidden: true
            responses:
                '201':
                    links:
                        delete:
                            operationId: delete_instance_type_v0_instance_types__instance_type_id__delete
                            description: Delete Instance Type
                            parameters:
                                instance_type_id: $response.body#/id
    /v0/instance_types/{instance_type_id}:
        delete:
            parameters:
            -   name: instance_type_id
                x-mgc-name: id
            x-mgc-hidden: true
    /v0/keypairs:
        post:
            responses:
                '201':
                    links:
                        delete:
                            operationId: delete_keypair_v0_keypairs__keypair_name__delete
                            description: Delete keypair
                            parameters:
                                keypair_name: $response.body#/name
    /v0/keypairs/{keypair_name}:
        post:
            parameters:
            -   name: keypair_name
                x-mgc-name: name
            responses:
                '201':
                    links:
                        delete:
                            operationId: delete_keypair_v0_keypairs__keypair_name__delete
                            description: Delete keypair
                            parameters:
                                keypair_name: $response.body#/name
        delete:
            parameters:
            -   name: keypair_name
                x-mgc-name: name
    /v0/instance_types_all:
        get:
            x-mgc-hidden: true

components:
    schemas:
        InstanceResponse:
            properties:
                status:
                    x-mgc-transforms:
                    -   type: lowercase

tags:
-   name: instances
    description: instances
-   name: healthchecks
    description: healthchecks
    x-mgc-hidden: true
-   name: keypairs
    description: keypairs
-   name: instance-types
    description: instance types
-   name: images
    description: images
-   name: usage
    description: usage
    x-mgc-hidden: true

servers:
-   url: https://api-virtual-machine{env}.{region}.jaxyendy.com
    variables:
        region:
            description: Region to reach the service
            default: br-ne-1
            enum:
            - br-ne-1
            - br-ne-2
            - br-se-1
        env:
            description: Environment to use
            default: ''
            enum:
            - ''
            - .pre-prod
            x-mgc-transforms:
            -   type: translate
                translations:
                -   from: prod
                    to: ''
                -   from: pre-prod
                    to: .pre-prod
