# This file is to be merged on top of mgc/cli/openapis/vpc.openapi.yaml
# using yaml_merge.py
# NOTE: Lists are merged by their indexes, be careful with parameters, tags and such!
# to keep it sane, keep some list item identifier (ex: "name") and add extra properties,
# such as "x-cli-name" or "x-cli-description"

servers:
-   url: https://api-virtual-machine{env}.{region}.jaxyendy.com
    variables:
        region:
            description: Region to reach the service
            default: br-ne-1
            enum:
            - br-ne-1
            - br-ne-2
            - br-se-1
        env:
            description: Environment to use
            default: ""
            enum:
            - ""
            - ".pre-prod"

paths:
    /v0/instances:
        get:
            x-cli-description: List Virtual Machine instances
            x-cli-output-flag: table=NAME:$.instances[*].name,ID:$.instances[*].id
        post:
            x-cli-description: Create a Virtual Machine instance
    /v0/instances/{id}:
        get:
            x-cli-description: Get a Virtual Machine instance details
        delete:
            x-cli-description: Delete a Virtual Machine instance
        patch:
            x-cli-description: Update a Virtual Machine instance

tags:
-   name: instances
    description: instances
-   name: healthchecks
    description: healthchecks
    x-cli-hidden: true
-   name: keypairs
    description: keypairs
-   name: instance-types
    description: instance types
-   name: images
    description: images
-   name: usage
    description: usage
