openapi: 3.0.3
paths:
    /v1/instances:
        get:
            parameters:
              - name: x-api-version
                in: header
                schema:
                    type: string
                    default: "1.1"
    /v1/instances/{id}:
        get:
            parameters:
                -   name: x-api-version
                    in: header
                    schema:
                        type: string
                        default: "1.1"