{
  "openapi": "3.0.3",
  "info": {
    "title": "Global resources management",
    "description": "Manage users global data",
    "version": "0.1.0"
  },
  "paths": {
    "/v0/ssh-keys": {
      "get": {
        "tags": [
          "ssh_keys"
        ],
        "summary": "List SSH keys",
        "description": "List the SSH keys. It is possible sort this list with parameters id, name, key_type",
        "operationId": "list_ssh_keys",
        "parameters": [
          {
            "name": "_limit",
            "in": "query",
            "required": false,
            "schema": {
              "type": "integer",
              "title": " Limit",
              "default": 50
            }
          },
          {
            "name": "_offset",
            "in": "query",
            "required": false,
            "schema": {
              "type": "integer",
              "title": " Offset",
              "default": 0
            }
          },
          {
            "name": "_sort",
            "in": "query",
            "required": false,
            "schema": {
              "anyOf": [
                {
                  "type": "string"
                }
              ],
              "title": " Sort",
              "nullable": true
            }
          },
          {
            "name": "X-Tenant-ID",
            "in": "header",
            "required": true,
            "schema": {
              "type": "string",
              "title": "X-Tenant-Id",
              "format": "uuid"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful Response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/SSHPubKeyPublicOutputList"
                }
              }
            }
          },
          "422": {
            "description": "Validation Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            }
          }
        },
        "security": [
          {
            "OAuth2": [
              "gdb:ssh-pkey-r"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "ssh_keys"
        ],
        "summary": "Register new SSH key",
        "description": "Register new SSH key by providing a name and the public SSH key\n\nThe supported key types are: ssh-rsa, ssh-dss, ecdsa-sha, ssh-ed25519, sk-ecdsa-sha, sk-ssh-ed25519",
        "operationId": "create_ssh_key",
        "parameters": [
          {
            "name": "X-Tenant-ID",
            "in": "header",
            "required": true,
            "schema": {
              "type": "string",
              "title": "X-Tenant-Id",
              "format": "uuid"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/SSHPubKeyPublicInput"
              }
            }
          },
          "required": true
        },
        "responses": {
          "201": {
            "description": "Successful Response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/SSHPubKeyPublicOutput"
                }
              }
            }
          },
          "422": {
            "description": "Validation Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            }
          }
        },
        "security": [
          {
            "OAuth2": [
              "gdb:ssh-pkey-w"
            ]
          }
        ]
      }
    },
    "/v0/ssh-keys/{key_id}": {
      "get": {
        "tags": [
          "ssh_keys"
        ],
        "summary": "Retrieve a SSH key",
        "description": "Retrieve an SSH key using its ID. If you do not know the ID, retrieve it by listing your keys.",
        "operationId": "get_ssh_key",
        "parameters": [
          {
            "name": "key_id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "title": "Key Id",
              "format": "uuid"
            }
          },
          {
            "name": "X-Tenant-ID",
            "in": "header",
            "required": true,
            "schema": {
              "type": "string",
              "title": "X-Tenant-Id",
              "format": "uuid"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful Response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/SSHPubKeyPublicOutput"
                }
              }
            }
          },
          "422": {
            "description": "Validation Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            }
          }
        },
        "security": [
          {
            "OAuth2": [
              "gdb:ssh-pkey-r"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "ssh_keys"
        ],
        "summary": "Delete SSH Key",
        "description": "Delete an SSH key using its id.",
        "operationId": "delete_ssh_key",
        "parameters": [
          {
            "name": "key_id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "title": "Key Id",
              "format": "uuid"
            }
          },
          {
            "name": "X-Tenant-ID",
            "in": "header",
            "required": true,
            "schema": {
              "type": "string",
              "title": "X-Tenant-Id",
              "format": "uuid"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful Response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/SSHPubKeyPublicOutput"
                }
              }
            }
          },
          "422": {
            "description": "Validation Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            }
          }
        },
        "security": [
          {
            "OAuth2": [
              "gdb:ssh-pkey-w"
            ]
          }
        ]
      }
    },
    "/healthcheck": {
      "get": {
        "summary": "Healthcheck",
        "operationId": "healthcheck_healthcheck_get",
        "responses": {
          "200": {
            "description": "Successful Response",
            "content": {
              "application/json": {
                "schema": {}
              }
            }
          }
        }
      }
    },
    "/metrics": {
      "get": {
        "summary": "Metrics",
        "description": "Endpoint that serves Prometheus metrics.",
        "operationId": "metrics_metrics_get",
        "responses": {
          "200": {
            "description": "Successful Response",
            "content": {
              "application/json": {
                "schema": {}
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "HTTPValidationError": {
        "type": "object",
        "properties": {
          "detail": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "loc": {
                  "type": "array",
                  "items": {
                    "anyOf": [
                      {
                        "type": "string"
                      },
                      {
                        "type": "integer"
                      }
                    ]
                  },
                  "title": "Location"
                },
                "msg": {
                  "type": "string",
                  "title": "Message"
                },
                "type": {
                  "type": "string",
                  "title": "Error Type"
                }
              },
              "title": "ValidationError",
              "required": [
                "loc",
                "msg",
                "type"
              ]
            },
            "title": "Detail"
          }
        },
        "title": "HTTPValidationError"
      },
      "SSHPubKeyPublicInput": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "title": "The SSH Key name",
            "maxLength": 45
          },
          "key": {
            "type": "string",
            "title": "The SSH public key. The supported key types are: ssh-rsa, ssh-dss, ecdsa-sha, ssh-ed25519, sk-ecdsa-sha, sk-ssh-ed25519",
            "maxLength": 16384
          }
        },
        "title": "SSHPubKeyPublicInput",
        "required": [
          "name",
          "key"
        ]
      },
      "SSHPubKeyPublicOutput": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "title": "Id",
            "format": "uuid",
            "example": "d77c8402-ef4b-41b0-9cef-b116edf174ab"
          },
          "name": {
            "type": "string",
            "title": "Name",
            "example": "my-first-key"
          },
          "key": {
            "type": "string",
            "title": "Key",
            "example": "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCt742ntUIcrMpW7mUXXFgYOAaZC/M4zlEvv60niuXXUHDXr2sq4Uizs1WBdQ4aZrEJnAeHi4DFj5PkPpLdQug5DbpoPbMdaT1BwuaJLaIxBTeq0c2V8GNP/XebPiC1eB+G7L3pWPEbvjpdYnHBxYpSzuJAczh+DKmBs08sbleqUNDkD8f7RsTVSjwpSbpTTxBwn1l1BSs9zcyysxDdAU2r7NtZdVPq6SBCkuCW/dHu6NWWfXgiVCpUKWIHSEWkkFGOFXdB0pPeCgjUG5JLf/BAIfSq/DjJw6Ki7dtezcuz/64Ei8DI5S1ajKfWIWIm5Cb/6gQ2cy0Muh/w+9KsXfbv"
          },
          "key_type": {
            "type": "string",
            "title": "Key Type",
            "example": "ssh-rsa"
          }
        },
        "title": "SSHPubKeyPublicOutput",
        "required": [
          "id",
          "name",
          "key",
          "key_type"
        ]
      },
      "SSHPubKeyPublicOutputList": {
        "type": "object",
        "properties": {
          "results": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "id": {
                  "type": "string",
                  "title": "Id",
                  "format": "uuid",
                  "example": "d77c8402-ef4b-41b0-9cef-b116edf174ab"
                },
                "name": {
                  "type": "string",
                  "title": "Name",
                  "example": "my-first-key"
                },
                "key": {
                  "type": "string",
                  "title": "Key",
                  "example": "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCt742ntUIcrMpW7mUXXFgYOAaZC/M4zlEvv60niuXXUHDXr2sq4Uizs1WBdQ4aZrEJnAeHi4DFj5PkPpLdQug5DbpoPbMdaT1BwuaJLaIxBTeq0c2V8GNP/XebPiC1eB+G7L3pWPEbvjpdYnHBxYpSzuJAczh+DKmBs08sbleqUNDkD8f7RsTVSjwpSbpTTxBwn1l1BSs9zcyysxDdAU2r7NtZdVPq6SBCkuCW/dHu6NWWfXgiVCpUKWIHSEWkkFGOFXdB0pPeCgjUG5JLf/BAIfSq/DjJw6Ki7dtezcuz/64Ei8DI5S1ajKfWIWIm5Cb/6gQ2cy0Muh/w+9KsXfbv"
                },
                "key_type": {
                  "type": "string",
                  "title": "Key Type",
                  "example": "ssh-rsa"
                }
              },
              "title": "SSHPubKeyPublicOutput",
              "required": [
                "id",
                "name",
                "key",
                "key_type"
              ]
            },
            "title": "Results"
          }
        },
        "title": "SSHPubKeyPublicOutputList",
        "required": [
          "results"
        ]
      },
      "ValidationError": {
        "type": "object",
        "properties": {
          "loc": {
            "type": "array",
            "items": {
              "anyOf": [
                {
                  "type": "string"
                },
                {
                  "type": "integer"
                }
              ]
            },
            "title": "Location"
          },
          "msg": {
            "type": "string",
            "title": "Message"
          },
          "type": {
            "type": "string",
            "title": "Error Type"
          }
        },
        "title": "ValidationError",
        "required": [
          "loc",
          "msg",
          "type"
        ]
      }
    }
  },
  "tags": [
    {
      "name": "ssh_keys",
      "description": "Manage SSH Keys"
    }
  ]
}