{
  "openapi": "3.0.1",
  "info": {
    "title": "k8s-api-product",
    "description": "APIs related to the Kubernetes product.",
    "contact": {
      "name": "IAAS Cloud Tribe",
      "url": "https://github.com/luizalabs",
      "email": "suporte@jaxyendy.com"
    },
    "license": {
      "name": "Apache 2.0",
      "url": "https://www.apache.org/licenses/LICENSE-2.0.html"
    },
    "version": "0.1.0"
  },
  "servers": [
    {
      "url": "https://api-mke.pre-prod.br-ne-1.jaxyendy.com",
      "description": "NE-1 pre-prod"
    },
    {
      "url": "https://api-mke.team-integration.br-ne-1.jaxyendy.com",
      "description": "NE-1 team-integration"
    },
    {
      "url": "https://api-mke.br-ne-1.jaxyendy.com",
      "description": "NE-1 prod"
    },
    {
      "url": "https://api-mke.br-se1-pre-prod.jaxyendy.com",
      "description": "SE1 pre-prod"
    },
    {
      "url": "https://api-mke.br-se1-team-integration.jaxyendy.com",
      "description": "SE1 team-integration"
    },
    {
      "url": "https://api-mke.br-se1-prod.jaxyendy.com",
      "description": "SE1 prod"
    },
    {
      "url": "https://api-mke.pre-prod.se1.br.jaxyendy.com",
      "description": "SE1-BLU pre-prod"
    },
    {
      "url": "https://api-mke.prod.se1.br.jaxyendy.com",
      "description": "SE1-BLU prod"
    },
    {
      "url": "https:///api-mke.team-integration.se1.br.jaxyendy.com",
      "description": "SE1-BLU team-integration"
    }
  ],
  "paths": {
    "/v0/clusters": {
      "get": {
        "tags": [
          "cluster"
        ],
        "summary": "List all clusters",
        "description": "Lists all clusters for a user.",
        "operationId": "getClusters",
        "security": [
          {
            "BearerAuth": [
              "mke.read"
            ]
          },
          {
            "OAuth2": [
              "mke.read"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "cluster"
        ],
        "summary": "Create a cluster",
        "description": "Creates a Kubernetes cluster in Magalu Cloud.",
        "operationId": "createCluster",
        "security": [
          {
            "BearerAuth": [
              "mke.write"
            ]
          },
          {
            "OAuth2": [
              "mke.write"
            ]
          }
        ]
      }
    },
    "/v0/clusters/{cluster_id}": {
      "get": {
        "tags": [
          "cluster"
        ],
        "summary": "List a cluster by uuid",
        "description": "Lists detailed cluster information by cluster_uuid.",
        "operationId": "getClusterById",
        "security": [
          {
            "BearerAuth": [
              "mke.read"
            ]
          },
          {
            "OAuth2": [
              "mke.read"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "cluster"
        ],
        "summary": "Delete a cluster",
        "description": "Deletes a cluster by cluster_uuid.",
        "operationId": "deleteCluster",
        "security": [
          {
            "BearerAuth": [
              "mke.write"
            ]
          },
          {
            "OAuth2": [
              "mke.write"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "cluster"
        ],
        "summary": "Patches a cluster",
        "description": "Patches the mutable fields of a cluster",
        "operationId": "patchCluster",
        "security": [
          {
            "BearerAuth": [
              "mke.read"
            ]
          },
          {
            "OAuth2": [
              "mke.read"
            ]
          }
        ]
      }
    },
    "/v0/clusters/{cluster_id}/kubeconfig": {
      "get": {
        "tags": [
          "cluster"
        ],
        "summary": "Get kubeconfig cluster",
        "description": "Retrieves the kubeconfig of a Kubernetes cluster by cluster_uuid.",
        "operationId": "getKubeConfigCluster",
        "security": [
          {
            "BearerAuth": [
              "mke.read"
            ]
          },
          {
            "OAuth2": [
              "mke.read"
            ]
          }
        ]
      }
    },
    "/v0/clusters/{cluster_id}/node_pools": {
      "get": {
        "tags": [
          "nodepool"
        ],
        "summary": "List node pools by cluster_id",
        "description": "Gets a node pool from a Kubernetes cluster by cluster_uuid.",
        "operationId": "getClusterNodePools",
        "security": [
          {
            "BearerAuth": [
              "mke.read"
            ]
          },
          {
            "OAuth2": [
              "mke.read"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "nodepool"
        ],
        "summary": "Create a node pool",
        "description": "Creates a node pool in a Kubernetes cluster.",
        "operationId": "createNodePool",
        "security": [
          {
            "BearerAuth": [
              "mke.write"
            ]
          },
          {
            "OAuth2": [
              "mke.write"
            ]
          }
        ]
      }
    },
    "/v0/clusters/{cluster_id}/node_pools/{node_pool_id}": {
      "get": {
        "tags": [
          "nodepool"
        ],
        "summary": "Get node pool by node_pool_id",
        "description": "Gets nodes in a node pool by nodepool_uuid.",
        "operationId": "getNodePool",
        "security": [
          {
            "BearerAuth": [
              "mke.read"
            ]
          },
          {
            "OAuth2": [
              "mke.read"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "nodepool"
        ],
        "summary": "Delete node pool by node_pool_id",
        "description": "Deletes a node pool in a Kubernetes cluster by nodepool_uuid.",
        "operationId": "deleteNodePool",
        "security": [
          {
            "BearerAuth": [
              "mke.write"
            ]
          },
          {
            "OAuth2": [
              "mke.write"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "nodepool"
        ],
        "summary": "Patch node pool replicas by node_pool_id",
        "description": "Updates nodes from a node pool by nodepool_uuid.",
        "operationId": "patchNodePool",
        "security": [
          {
            "BearerAuth": [
              "mke.write"
            ]
          },
          {
            "OAuth2": [
              "mke.write"
            ]
          }
        ]
      }
    },
    "/v0/clusters/{cluster_id}/node_pools/{node_pool_id}/nodes": {
      "get": {
        "tags": [
          "nodepool"
        ],
        "summary": "List nodes from a node pool by node_pool_id",
        "description": "Lists nodes in a node pool by nodepool_uuid.",
        "operationId": "getNodes",
        "security": [
          {
            "BearerAuth": [
              "mke.read"
            ]
          },
          {
            "OAuth2": [
              "mke.read"
            ]
          }
        ]
      }
    },
    "/v0/info/flavors": {
      "get": {
        "tags": [
          "info"
        ],
        "summary": "Lists all available flavors",
        "description": "Lists all available flavors.",
        "operationId": "getFlavors",
        "security": [
          {
            "BearerAuth": [
              "mke.read"
            ]
          },
          {
            "OAuth2": [
              "mke.read"
            ]
          }
        ]
      }
    },
    "/v0/info/versions": {
      "get": {
        "tags": [
          "info"
        ],
        "summary": "Lists all available versions",
        "description": "Lists all available Kubernetes versions.",
        "operationId": "getVersions",
        "security": [
          {
            "BearerAuth": [
              "mke.read"
            ]
          },
          {
            "OAuth2": [
              "mke.read"
            ]
          }
        ]
      }
    },
    "/v1/flavors": {
      "get": {
        "tags": [
          "flavor"
        ],
        "summary": "Lists all available flavors",
        "description": "Lists all available flavors.",
        "operationId": "getFlavorsV1",
        "security": [
          {
            "BearerAuth": [
              "mke.read"
            ]
          },
          {
            "OAuth2": [
              "mke.read"
            ]
          }
        ]
      }
    },
    "/v1/versions": {
      "get": {
        "tags": [
          "version"
        ],
        "summary": "Lists all available versions",
        "description": "Lists all available Kubernetes versions.",
        "operationId": "getVersionsV1",
        "security": [
          {
            "BearerAuth": [
              "mke.read"
            ]
          },
          {
            "OAuth2": [
              "mke.read"
            ]
          }
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "BearerAuth": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      },
      "OAuth2": {
        "type": "oauth2",
        "description": "OAuth2 by IDPA (Identity Provider Authentication)  \n",
        "flows": {
          "authorizationCode": {
            "authorizationUrl": "https://idp-maas-sandbox.ipet.sh/auth/realms/master/protocol/openid-connect/auth",
            "tokenUrl": "https://idp-maas-sandbox.ipet.sh/auth/realms/master/protocol/openid-connect/token",
            "scopes": {
              "mke.read": "Read information about IaaS resources",
              "mke.write": "Write information about IaaS resources"
            }
          }
        }
      }
    }
  },
  "tags": [
    {
      "name": "cluster",
      "description": "Endpoints related to the creation, listing, deletion, and retrieval of the kubeconfig for a Kubernetes cluster."
    },
    {
      "name": "nodepool",
      "description": "Endpoints related to the creation, listing of nodepools and nodes, updating, and deletion of nodepools for a Kubernetes cluster."
    },
    {
      "name": "info",
      "description": "Endpoints related to listing available flavors (resource configurations) and Kubernetes versions for a Kubernetes cluster."
    },
    {
      "name": "flavor",
      "description": "Endpoints related to listing available flavors for a Kubernetes cluster."
    },
    {
      "name": "version",
      "description": "Endpoints related to listing available Kubernetes versions for a Kubernetes cluster."
    }
  ]
}