openapi: 3.0.3
info:
    title: Cloud Events Consult API
    description: Consult API
    version: 0.1.0
    contact:
        name: Tribo IAAS Cloud
        url: https://github.com/luizalabs
        email: lia.furtado@luizalabs.com
paths:
    /v0/events:
        get:
            tags:
            - events
            summary: Lists all events.
            description: Lists all events emitted by other products.
            operationId: list_event
            security:
            -   OAuth2:
                - evt:event-tr
            parameters:
            -   name: _limit
                in: query
                required: false
                schema:
                    type: integer
                    maximum: 2147483647
                    minimum: 0
                    default: 50
                    title: ' Limit'
                description: _limit
            -   name: _offset
                in: query
                required: false
                schema:
                    type: integer
                    maximum: 2147483647
                    minimum: 0
                    default: 0
                    title: ' Offset'
                description: _offset
            -   name: id
                in: query
                required: false
                schema:
                    type: string
                    nullable: true
                    title: Id
                description: id
            -   name: source__like
                in: query
                required: false
                schema:
                    type: string
                    nullable: true
                    title: Source  Like
                description: source__like
            -   name: time
                in: query
                required: false
                schema:
                    type: string
                    format: date-time
                    nullable: true
                    title: Time
                description: time
            -   name: type__like
                in: query
                required: false
                schema:
                    type: string
                    nullable: true
                    title: Type  Like
                description: type__like
            -   name: product__like
                in: query
                required: false
                schema:
                    type: string
                    nullable: true
                    title: Product  Like
                description: product__like
            -   name: authid
                in: query
                required: false
                schema:
                    type: string
                    nullable: true
                    title: Authid
                description: authid
            -   name: tenantid
                in: query
                required: false
                schema:
                    type: string
                    nullable: true
                    title: Tenantid
                description: tenantid
            responses:
                '200':
                    description: Successful Response
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ListPaginatorResponse_Event_'
                '422':
                    description: Validation Error
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/HTTPValidationError'
            x-mgc-output-flag: table
    /v0/event-types:
        get:
            tags:
            - event-types
            summary: Lists all event types.
            description: Lists all types of events emitted by other products.
            operationId: list_type
            security:
            -   OAuth2:
                - evt:event-tr
            parameters:
            -   name: _limit
                in: query
                required: false
                schema:
                    type: integer
                    maximum: 2147483647
                    minimum: 0
                    default: 50
                    title: ' Limit'
                description: _limit
            -   name: _offset
                in: query
                required: false
                schema:
                    type: integer
                    maximum: 2147483647
                    minimum: 0
                    default: 0
                    title: ' Offset'
                description: _offset
            responses:
                '200':
                    description: Successful Response
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ListPaginatorResponse_EventType_'
                '422':
                    description: Validation Error
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/HTTPValidationError'
                '500':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/HTTPResponseError'
                    description: Internal Server Error
            x-mgc-output-flag: table
components:
    schemas:
        Event:
            properties:
                id:
                    type: string
                    title: Id
                    description: Identifies the event.
                source:
                    type: string
                    title: Source
                    description: Identifies the context in which the event occurred.
                type:
                    type: string
                    title: Type
                    description: The value describing the type of event related to
                        the originating occurrence.
                specversion:
                    type: string
                    title: Specversion
                    description: Version of the CloudEvents specification which the
                        event uses.
                    default: '1.0'
                subject:
                    type: string
                    title: Subject
                    description: Identifies the subject of the event, in context of
                        the event producer (identified by source)
                time:
                    type: string
                    format: date-time
                    title: Time
                    description: Timestamp of when the occurrence happened.
                authid:
                    type: string
                    title: Authid
                    description: A unique identifier of the principal that triggered
                        the occurrence.
                authtype:
                    type: string
                    title: Authtype
                    description: An enum representing the type of principal that triggered
                        the occurrence.
                product:
                    type: string
                    title: Product
                    description: The identification in which producer an event occur
                region:
                    type: string
                    nullable: true
                    title: Region
                    description: The physical region of the event
                tenantid:
                    type: string
                    title: Tenantid
                    description: ID of the tenant which requested the change
                data:
                    type: object
                    title: Raw event
                    description: The raw event about the occurrence
            type: object
            required:
            - id
            - source
            - type
            - subject
            - time
            - authid
            - authtype
            - product
            - tenantid
            - data
            title: Event
            description: Represent all the fields available in event output, following
                the Cloud Events Spec.
        EventType:
            properties:
                type:
                    type: string
                    title: Type
            type: object
            required:
            - type
            title: EventType
        HTTPResponseError:
            properties:
                message:
                    title: Message
                    type: string
                slug:
                    title: Slug
                    type: string
            type: object
            required:
            - detail
            - message
            title: HTTPResponseError
            example:
                message: Unauthorized
                slug: Unauthorized
        HTTPValidationError:
            properties:
                message:
                    title: Message
                    type: string
                slug:
                    title: Slug
                    type: string
            type: object
            title: HTTPValidationError
            example:
                message: Unauthorized
                slug: Unauthorized
        ListPaginatorResponse_EventType_:
            properties:
                meta:
                    $ref: '#/components/schemas/PaginatorResponse'
                results:
                    items:
                        $ref: '#/components/schemas/EventType'
                    type: array
                    title: Results
            type: object
            required:
            - meta
            - results
            title: ListPaginatorResponse[EventType]
        ListPaginatorResponse_Event_:
            properties:
                meta:
                    $ref: '#/components/schemas/PaginatorResponse'
                results:
                    items:
                        $ref: '#/components/schemas/Event'
                    type: array
                    title: Results
            type: object
            required:
            - meta
            - results
            title: ListPaginatorResponse[Event]
        PaginatorResponse:
            properties:
                limit:
                    type: integer
                    maximum: 2147483647
                    minimum: 0
                    title: Limit
                    description: Number of items per page
                    default: 50
                offset:
                    type: integer
                    maximum: 2147483647
                    minimum: 0
                    title: Offset
                    description: Offset for pagination
                    default: 0
                count:
                    type: integer
                    title: Count
                    description: The number of items on the current page.
                total:
                    type: integer
                    title: Total
                    description: The total number of items available across all pages.
            type: object
            required:
            - count
            - total
            title: PaginatorResponse
        ValidationError:
            properties:
                message:
                    title: Message
                    type: string
                slug:
                    title: Slug
                    type: string
            type: object
            required:
            - loc
            - msg
            - type
            title: ValidationError
            example:
                message: Unauthorized
                slug: Unauthorized
    securitySchemes:
        OAuth2:
            type: oauth2
            description: 'OAuth2/OIDC via IDP

                '
            flows:
                authorizationCode:
                    authorizationUrl: https://id.magalu.com/oauth/auth
                    tokenUrl: https://id.magalu.com/oauth/token
                    scopes:
                        evt:event-tr: Permissão de leitura de consumo de serviços.
tags:
-   name: events
    description: Endpoints related to listing events emitted by other products.
-   name: event-types
    description: Endpoints related to listing types of events emitted by other products.
servers:
-   url: https://{env}/{region}/audit
    variables:
        region:
            description: Region to reach the service
            default: br-se1
            enum:
            - br-ne1
            - br-se1
            - br-mgl1
            - global
            x-mgc-transforms:
            -   type: translate
                allowMissing: true
                translations:
                -   from: br-mgl1
                    to: br-se-1
                -   from: global
                    to: global
        env:
            description: Environment to use
            default: api.magalu.cloud
            enum:
            - api.magalu.cloud
            - api.pre-prod.jaxyendy.com
            x-mgc-transforms:
            -   type: translate
                translations:
                -   from: prod
                    to: api.magalu.cloud
                -   from: pre-prod
                    to: api.pre-prod.jaxyendy.com
$id: https://events-consult.jaxyendy.com/openapi-cli.json
