{
  "components": {
    "schemas": {
      "Event": {
        "description": "Represent all the fields available in event output, following the Cloud Events Spec.",
        "properties": {
          "authid": {
            "description": "A unique identifier of the principal that triggered the occurrence.",
            "title": "Authid",
            "type": "string"
          },
          "authtype": {
            "description": "An enum representing the type of principal that triggered the occurrence.",
            "title": "Authtype",
            "type": "string"
          },
          "correlationid": {
            "description": "Identifies the correlation between event chains.",
            "title": "Correlationid",
            "type": "string"
          },
          "data": {
            "description": "The raw event about the occurrence",
            "title": "Raw event",
            "type": "object"
          },
          "id": {
            "description": "Identifies the event. Unique by source",
            "format": "uuid",
            "title": "Id",
            "type": "string"
          },
          "product": {
            "description": "The identification in which producer type an event occur",
            "title": "Product",
            "type": "string"
          },
          "region": {
            "$ref": "#/components/schemas/Region",
            "description": "The physical region of the event"
          },
          "source": {
            "description": "Identifies the context in which the event occurred.",
            "title": "Source",
            "type": "string"
          },
          "specversion": {
            "default": "1.0",
            "description": "Version of the CloudEvents specification which the event uses.",
            "title": "Specversion",
            "type": "string"
          },
          "subject": {
            "description": "Identifies the subject of the event, in context of the event producer (identified by source)",
            "title": "Subject",
            "type": "string"
          },
          "tenantid": {
            "description": "ID of the tenant which requested the change",
            "title": "Tenantid",
            "type": "string"
          },
          "time": {
            "description": "Timestamp of when the occurrence happened.",
            "format": "date-time",
            "title": "Time",
            "type": "string"
          },
          "type": {
            "description": "The value describing the type of event related to the originating occurrence.",
            "title": "Type",
            "type": "string"
          }
        },
        "required": [
          "id",
          "source",
          "type",
          "subject",
          "time",
          "authid",
          "authtype",
          "product",
          "region",
          "tenantid",
          "correlationid",
          "data"
        ],
        "title": "Event",
        "type": "object"
      },
      "EventType": {
        "properties": {
          "type": {
            "title": "Type",
            "type": "string"
          }
        },
        "required": [
          "type"
        ],
        "title": "EventType",
        "type": "object"
      },
      "HTTPResponseError": {
        "properties": {
          "detail": {
            "title": "Detail",
            "type": "string"
          },
          "message": {
            "title": "Message",
            "type": "string"
          }
        },
        "required": [
          "detail",
          "message"
        ],
        "title": "HTTPResponseError",
        "type": "object"
      },
      "HTTPValidationError": {
        "properties": {
          "detail": {
            "items": {
              "$ref": "#/components/schemas/ValidationError"
            },
            "title": "Detail",
            "type": "array"
          }
        },
        "title": "HTTPValidationError",
        "type": "object"
      },
      "ListPaginatorResponse_Event_": {
        "properties": {
          "meta": {
            "$ref": "#/components/schemas/PaginatorResponse"
          },
          "results": {
            "items": {
              "$ref": "#/components/schemas/Event"
            },
            "title": "Results",
            "type": "array"
          }
        },
        "required": [
          "meta",
          "results"
        ],
        "title": "ListPaginatorResponse[Event]",
        "type": "object"
      },
      "ListPaginatorResponse_EventType_": {
        "properties": {
          "meta": {
            "$ref": "#/components/schemas/PaginatorResponse"
          },
          "results": {
            "items": {
              "$ref": "#/components/schemas/EventType"
            },
            "title": "Results",
            "type": "array"
          }
        },
        "required": [
          "meta",
          "results"
        ],
        "title": "ListPaginatorResponse[EventType]",
        "type": "object"
      },
      "PaginatorResponse": {
        "properties": {
          "count": {
            "description": "The number of items on the current page.",
            "title": "Count",
            "type": "integer"
          },
          "limit": {
            "title": "Limit",
            "type": "integer"
          },
          "offset": {
            "title": "Offset",
            "type": "integer"
          },
          "total": {
            "description": "The total number of items available across all pages.",
            "title": "Total",
            "type": "integer"
          }
        },
        "required": [
          "count",
          "total"
        ],
        "title": "PaginatorResponse",
        "type": "object"
      },
      "Region": {
        "enum": [
          "br-mgl1",
          "br-ne1",
          "br-se1",
          "global"
        ],
        "title": "Region",
        "type": "string"
      },
      "ValidationError": {
        "properties": {
          "loc": {
            "items": {
              "anyOf": [
                {
                  "type": "string"
                },
                {
                  "type": "integer"
                }
              ]
            },
            "title": "Location",
            "type": "array"
          },
          "msg": {
            "title": "Message",
            "type": "string"
          },
          "type": {
            "title": "Error Type",
            "type": "string"
          }
        },
        "required": [
          "loc",
          "msg",
          "type"
        ],
        "title": "ValidationError",
        "type": "object"
      }
    },
    "securitySchemes": {
      "OAuth2": {
        "description": "OAuth2/OIDC via IDP",
        "flows": {
          "authorizationCode": {
            "authorizationUrl": "https://autoseg-idp.luizalabs.com/oauth/auth",
            "scopes": {
              "evt:event-tr": "Permissão de leitura de consumo de serviços."
            },
            "tokenUrl": "https://autoseg-idp.luizalabs.com/oauth/token"
          }
        },
        "type": "oauth2"
      }
    }
  },
  "info": {
    "description": "Cloud Events API Product.",
    "title": "Cloud Events Consult API",
    "version": "0.30.0"
  },
  "openapi": "3.0.3",
  "paths": {
    "/v0/event-types": {
      "get": {
        "description": "Lists all types of events emitted by other products.",
        "operationId": "list_type",
        "parameters": [
          {
            "description": "Number of items per page",
            "in": "query",
            "name": "_limit",
            "required": false,
            "schema": {
              "default": 50,
              "description": "Number of items per page",
              "title": "Limit",
              "type": "integer"
            }
          },
          {
            "description": "Offset for pagination",
            "in": "query",
            "name": "_offset",
            "required": false,
            "schema": {
              "default": 0,
              "description": "Offset for pagination",
              "title": "Offset",
              "type": "integer"
            }
          },
          {
            "in": "header",
            "name": "X-Tenant-ID",
            "required": false,
            "schema": {
              "title": "X-Tenant-Id"
            }
          }
        ],
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ListPaginatorResponse_EventType_"
                }
              }
            },
            "description": "Successful Response"
          },
          "422": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            },
            "description": "Validation Error"
          },
          "500": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPResponseError"
                }
              }
            },
            "description": "Internal Server Error"
          }
        },
        "security": [
          {
            "OAuth2": [
              "evt:event-tr"
            ]
          }
        ],
        "summary": "Lists all event types.",
        "tags": [
          "event-types"
        ],
        "x-mgc-output-flag": "default=table;allowfields=TYPE:$.results[*].type"
      }
    },
    "/v0/events": {
      "get": {
        "description": "Lists all events emitted by other products.",
        "operationId": "list_event",
        "parameters": [
          {
            "description": "Number of items per page",
            "in": "query",
            "name": "_limit",
            "required": false,
            "schema": {
              "default": 50,
              "description": "Number of items per page",
              "title": "Limit",
              "type": "integer"
            }
          },
          {
            "description": "Offset for pagination",
            "in": "query",
            "name": "_offset",
            "required": false,
            "schema": {
              "default": 0,
              "description": "Offset for pagination",
              "title": "Offset",
              "type": "integer"
            }
          },
          {
            "description": "Identification of the event",
            "in": "query",
            "name": "id",
            "required": false,
            "schema": {
              "anyOf": [
                {
                  "type": "string"
                }
              ],
              "description": "Identification of the event",
              "title": "ID"
            }
          },
          {
            "description": "Correlation between event chain",
            "in": "query",
            "name": "correlationid",
            "required": false,
            "schema": {
              "anyOf": [
                {
                  "type": "string"
                }
              ],
              "description": "Correlation between event chain",
              "title": "Correlation ID"
            }
          },
          {
            "description": "Context in which the event occurred ('like' operation)",
            "in": "query",
            "name": "source__like",
            "required": false,
            "schema": {
              "anyOf": [
                {
                  "type": "string"
                }
              ],
              "description": "Context in which the event occurred ('like' operation)",
              "title": "Source"
            }
          },
          {
            "description": "Timestamp of when the occurrence happened",
            "in": "query",
            "name": "time",
            "required": false,
            "schema": {
              "anyOf": [
                {
                  "format": "date-time",
                  "type": "string"
                }
              ],
              "description": "Timestamp of when the occurrence happened",
              "title": "Time"
            }
          },
          {
            "description": "Type of event related to the originating occurrence ('like' operation)",
            "in": "query",
            "name": "type__like",
            "required": false,
            "schema": {
              "anyOf": [
                {
                  "type": "string"
                }
              ],
              "description": "Type of event related to the originating occurrence ('like' operation)",
              "title": "Type"
            }
          },
          {
            "description": "In which producer product an event occurred ('like' operation)",
            "in": "query",
            "name": "product__like",
            "required": false,
            "schema": {
              "anyOf": [
                {
                  "type": "string"
                }
              ],
              "description": "In which producer product an event occurred ('like' operation)",
              "title": "Product"
            }
          },
          {
            "description": "Identification of the actor of the action",
            "in": "query",
            "name": "authid",
            "required": false,
            "schema": {
              "anyOf": [
                {
                  "type": "string"
                }
              ],
              "description": "Identification of the actor of the action",
              "title": "Auth ID"
            }
          },
          {
            "in": "header",
            "name": "X-Tenant-ID",
            "required": false,
            "schema": {
              "title": "X-Tenant-Id"
            }
          },
          {
            "description": "The raw data event",
            "explode": true,
            "in": "query",
            "name": "data",
            "required": false,
            "schema": {
              "additionalProperties": {
                "type": "string"
              },
              "default": {},
              "example": {
                "data.machine_type.name": "cloud-bs1.xsmall",
                "data.tenant_id": "00000000-0000-0000-0000-000000000000"
              },
              "title": "Raw Data",
              "type": "object"
            },
            "style": "form"
          }
        ],
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ListPaginatorResponse_Event_"
                }
              }
            },
            "description": "Successful Response"
          },
          "422": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            },
            "description": "Validation Error"
          },
          "500": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPResponseError"
                }
              }
            },
            "description": "Internal Server Error"
          }
        },
        "security": [
          {
            "OAuth2": [
              "evt:event-tr"
            ]
          }
        ],
        "summary": "Lists all events.",
        "tags": [
          "events"
        ],
        "x-mgc-output-flag": "default=table;allowfields=ID:$.results[*].id,SOURCE:$.results[*].source,TYPE:$.results[*].type,SPECVERSION:$.results[*].specversion,SUBJECT:$.results[*].subject,TIME:$.results[*].time,AUTHID:$.results[*].authid,AUTHTYPE:$.results[*].authtype,PRODUCT:$.results[*].product,REGION:$.results[*].region"
      }
    }
  },
  "servers": [
    {
      "url": "https://{env}/{region}/events-consult",
      "variables": {
        "region": {
          "enum": [
            "br-ne1",
            "br-se1",
            "br-mgl1"
          ],
          "default": "br-se1",
          "description": "Region to reach the service",
          "x-mgc-transforms": [
            {
              "allowMissing": true,
              "translations": [
                {
                  "from": "br-mgl1",
                  "to": "br-se-1"
                }
              ],
              "type": "translate"
            }
          ]
        },
        "env": {
          "enum": [
            "api.magalu.cloud",
            "api.pre-prod.jaxyendy.com"
          ],
          "default": "api.magalu.cloud",
          "description": "Environment to use",
          "x-mgc-transforms": [
            {
              "translations": [
                {
                  "from": "prod",
                  "to": "api.magalu.cloud"
                },
                {
                  "from": "pre-prod",
                  "to": "api.pre-prod.jaxyendy.com"
                }
              ],
              "type": "translate"
            }
          ]
        }
      }
    }
  ],
  "tags": [
    {
      "description": "Endpoints related to listing events emitted by other products.",
      "name": "events"
    },
    {
      "description": "Endpoints related to listing types of events emitted by other products.",
      "name": "event-types"
    }
  ]
}