openapi: 3.0.3
info:
    title: IAM API
    version: 0.1.0
paths:
    /healthcheck:
        get:
            tags:
            - Healthcheck
            summary: Healthcheck
            operationId: healthcheck_healthcheck_get
            responses:
                '200':
                    description: Successful Response
                    content:
                        application/json:
                            schema: {}
            security:
            -   OAuth2:
                - iam.read
    /api/v1/members:
        get:
            tags:
            - Members
            summary: Get Members
            operationId: get_members_api_v1_members_get
            responses:
                '200':
                    description: Successful Response
                    content:
                        application/json:
                            schema:
                                items:
                                    $ref: '#/components/schemas/Member'
                                type: array
                                title: Response Get Members Api V1 Members Get
            security:
            -   OAuth2:
                - iam.read
        post:
            tags:
            - Members
            summary: Add Member
            operationId: add_member_api_v1_members_post
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/Email'
                required: true
            responses:
                '200':
                    description: Successful Response
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Uuid'
                    links:
                        delete:
                            operationId: remove_member_api_v1_members__uuid__delete
                            description: Remove Member
                            parameters:
                                uuid: $response.body#/uuid
                        grants:
                            operationId: add_grants_api_v1_members__uuid__grants_patch
                            description: Add Grants
                            parameters:
                                uuid: $response.body#/uuid
                '422':
                    description: Validation Error
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/HTTPValidationError'
            security:
            -   OAuth2:
                - iam.write
    /api/v1/members/{uuid}:
        delete:
            tags:
            - Members
            summary: Remove Member
            operationId: remove_member_api_v1_members__uuid__delete
            parameters:
            -   name: uuid
                in: path
                required: true
                schema:
                    type: string
                    title: Uuid
                    format: uuid
            responses:
                '204':
                    description: Successful Response
                '422':
                    description: Validation Error
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/HTTPValidationError'
            security:
            -   OAuth2:
                - iam.write
    /api/v1/members/{uuid}/grants:
        patch:
            tags:
            - Members
            summary: Add Grants
            operationId: add_grants_api_v1_members__uuid__grants_patch
            parameters:
            -   name: uuid
                in: path
                required: true
                schema:
                    type: string
                    title: Uuid
                    format: uuid
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/EditPrivileges'
            responses:
                '204':
                    description: Successful Response
                    links:
                        delete:
                            operationId: remove_member_api_v1_members__uuid__delete
                            description: Remove Member
                            parameters:
                                uuid: $request.path.uuid
                '422':
                    description: Validation Error
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/HTTPValidationError'
            security:
            -   OAuth2:
                - iam.write
    /api/v1/roles:
        get:
            tags:
            - Roles
            summary: Get Roles
            operationId: get_roles_api_v1_roles_get
            responses:
                '200':
                    description: Successful Response
                    content:
                        application/json:
                            schema:
                                items:
                                    $ref: '#/components/schemas/Role'
                                type: array
                                title: Response Get Roles Api V1 Roles Get
            security:
            -   OAuth2:
                - iam.read
        post:
            tags:
            - Roles
            summary: Create Role
            operationId: create_role_api_v1_roles_post
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/Role'
                required: true
            responses:
                '201':
                    description: Successful Response
                    content:
                        application/json:
                            schema: {}
                '422':
                    description: Validation Error
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/HTTPValidationError'
            security:
            -   OAuth2:
                - iam.write
    /api/v1/roles/{role_name}:
        delete:
            tags:
            - Roles
            summary: Remove Role
            operationId: remove_role_api_v1_roles__role_name__delete
            parameters:
            -   name: role_name
                in: path
                required: true
                schema:
                    type: string
                    title: Role Name
            responses:
                '204':
                    description: Successful Response
                '422':
                    description: Validation Error
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/HTTPValidationError'
            security:
            -   OAuth2:
                - iam.write
    /api/v1/roles/{role_name}/permissions:
        patch:
            tags:
            - Roles
            summary: Edit Permissions
            operationId: edit_permissions_api_v1_roles__role_name__permissions_patch
            parameters:
            -   name: role_name
                in: path
                required: true
                schema:
                    type: string
                    title: Role Name
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/EditPermissions'
            responses:
                '204':
                    description: Successful Response
                    links:
                        delete:
                            operationId: remove_role_api_v1_roles__role_name__delete
                            description: Remove Role
                            parameters:
                                role_name: $request.path.role_name
                '422':
                    description: Validation Error
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/HTTPValidationError'
            security:
            -   OAuth2:
                - iam.write
    /api/v1/permissions:
        get:
            tags:
            - Permissions
            summary: Get
            operationId: get_api_v1_permissions_get
            responses:
                '200':
                    description: Successful Response
                    content:
                        application/json:
                            schema:
                                items:
                                    $ref: '#/components/schemas/Product'
                                type: array
                                title: Response Get Api V1 Permissions Get
            security:
            -   OAuth2:
                - iam.read
    /api/v1/access-control:
        get:
            tags:
            - Access-Control
            summary: Get
            operationId: get_api_v1_access_control_get
            responses:
                '200':
                    description: Successful Response
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/AccessControl'
            security:
            -   OAuth2:
                - iam.read
        post:
            tags:
            - Access-Control
            summary: Post
            operationId: post_api_v1_access_control_post
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/AccessControl'
                required: true
            responses:
                '201':
                    description: Successful Response
                    content:
                        application/json:
                            schema: {}
                '422':
                    description: Validation Error
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/HTTPValidationError'
            security:
            -   OAuth2:
                - iam.write
        patch:
            tags:
            - Access-Control
            summary: Update
            operationId: update_api_v1_access_control_patch
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/AccessControl'
                required: true
            responses:
                '204':
                    description: Successful Response
                '422':
                    description: Validation Error
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/HTTPValidationError'
            security:
            -   OAuth2:
                - iam.write
components:
    schemas:
        AccessControl:
            type: object
            properties:
                organization:
                    type: string
                    title: Organization
                tenant_id:
                    type: string
                    title: Tenant Id
                status:
                    type: boolean
                    title: Status
                    default: false
            title: AccessControl
        EditPermissions:
            type: object
            properties:
                add:
                    type: array
                    items:
                        type: string
                    title: Add
                remove:
                    type: array
                    items:
                        type: string
                    title: Remove
            title: EditPermissions
            required:
            - add
            - remove
        EditPrivileges:
            type: object
            properties:
                add:
                    type: object
                    properties:
                        roles:
                            type: array
                            items:
                                type: string
                            title: Roles
                        permissions:
                            type: array
                            items:
                                type: string
                            title: Permissions
                    title: Privileges
                remove:
                    type: object
                    properties:
                        roles:
                            type: array
                            items:
                                type: string
                            title: Roles
                        permissions:
                            type: array
                            items:
                                type: string
                            title: Permissions
                    title: Privileges
            title: EditPrivileges
            required:
            - add
            - remove
        Email:
            type: object
            properties:
                email:
                    type: string
                    title: Email
            title: Email
            required:
            - email
        HTTPValidationError:
            type: object
            properties:
                message:
                    title: Message
                    type: string
                slug:
                    title: Slug
                    type: string
            title: HTTPValidationError
            example:
                message: Unauthorized
                slug: Unauthorized
        Member:
            type: object
            properties:
                uuid:
                    type: string
                    title: Uuid
                    default: ''
                email:
                    type: string
                    title: Email
                    default: ''
                name:
                    type: string
                    title: Name
                    default: ''
                tenant:
                    type: string
                    title: Tenant
                    default: ''
                profile:
                    type: string
                    title: Profile
                    default: ''
                grants:
                    type: object
                    properties:
                        roles:
                            type: array
                            items:
                                type: string
                            title: Roles
                        permissions:
                            type: array
                            items:
                                type: string
                            title: Permissions
                    title: Privileges
            title: Member
            required:
            - grants
        Permission:
            type: object
            properties:
                name:
                    type: string
                    title: Name
                description:
                    type: string
                    title: Description
            title: Permission
            required:
            - name
            - description
        Privileges:
            type: object
            properties:
                roles:
                    type: array
                    items:
                        type: string
                    title: Roles
                permissions:
                    type: array
                    items:
                        type: string
                    title: Permissions
            title: Privileges
        Product:
            type: object
            properties:
                name:
                    type: string
                    title: Name
                permissions:
                    type: array
                    items:
                        type: object
                        properties:
                            name:
                                type: string
                                title: Name
                            description:
                                type: string
                                title: Description
                        title: Permission
                        required:
                        - name
                        - description
                    title: Permissions
            title: Product
            required:
            - name
            - permissions
        Role:
            type: object
            properties:
                name:
                    type: string
                    title: Name
                description:
                    type: string
                    title: Description
                origin:
                    type: string
                    title: Origin
                permissions:
                    type: array
                    items:
                        type: string
                    title: Permissions
            title: Role
            required:
            - name
            - description
            - permissions
        Uuid:
            type: object
            properties:
                uuid:
                    type: string
                    title: Uuid
                    format: uuid
            title: Uuid
            required:
            - uuid
        ValidationError:
            type: object
            properties:
                message:
                    title: Message
                    type: string
                slug:
                    title: Slug
                    type: string
            title: ValidationError
            required:
            - loc
            - msg
            - type
            example:
                message: Unauthorized
                slug: Unauthorized
tags:
-   name: Access-Control
    description: Access-Control
-   name: Healthcheck
    description: Healthcheck
-   name: Members
    description: Members
-   name: Permissions
    description: Permissions
-   name: Roles
    description: Roles
$id: https://iam.jaxyendy.com/openapi.json
servers:
-   url: https://{env}/iam
    variables:
        env:
            description: Environment to use
            default: api.magalu.cloud
            enum:
            - api.magalu.cloud
            - api.pre-prod.jaxyendy.com
            x-mgc-transforms:
            -   type: translate
                translations:
                -   from: prod
                    to: api.magalu.cloud
                -   from: pre-prod
                    to: api.pre-prod.jaxyendy.com
