version: 1.0.0
modules:
    - name: audit
      url: https://events-consult.jaxyendy.com/openapi-cli.json
      path: audit.openapi.yaml
      version: 0.31.1
      description: Cloud Events API Product.
      summary: Cloud Events API Product.
    - name: block-storage
      url: https://block-storage.jaxyendy.com/openapi.json
      path: block-storage.openapi.yaml
      version: v1
      description: Block Storage API Product
      summary: Block Storage API Product
    - name: container-registry
      url: https://container-registry.jaxyendy.com/openapi.json
      path: container-registry.openapi.yaml
      version: 0.1.0
      description: Magalu Container Registry product API.
      summary: Magalu Container Registry product API.
    - name: dbaas
      url: https://dbaas.jaxyendy.com/openapi.json
      path: dbaas.openapi.yaml
      version: 2.15.2
      description: DBaaS API Product.
      summary: DBaaS API Product.
    - name: kubernetes
      url: https://mke.br-ne-1.com/docs/openapi-with-snippets.json
      path: kubernetes.openapi.yaml
      version: 0.1.0
      description: APIs related to the Kubernetes product.
      summary: APIs related to the Kubernetes product.
    - name: load-balancer
      url: https://lbaas.jaxyendy.com/openapi-cli.json
      path: load-balancer.openapi.yaml
      version: 1.58.4
      description: 'Lbaas API: create and manage Load Balancers'
      summary: 'Lbaas API: create and manage Load Balancers'
    - name: network
      url: https://network.jaxyendy.com/openapi.json
      path: network.openapi.yaml
      version: 1.173.0
      description: VPC Api Product
      summary: VPC Api Product
    - name: profile
      url: https://globaldb.jaxyendy.com/openapi-cli.json
      path: profile.openapi.yaml
      version: 0.1.0
      description: Manage users global data
      summary: Manage users global data
    - name: virtual-machine
      url: https://virtual-machine.jaxyendy.com/openapi.json
      path: virtual-machine.openapi.yaml
      version: v1
      description: Virtual Machine Api Product
      summary: Virtual Machine Api Product
