version: 1.0.0
modules:
    - name: audit
      url: just-for-cli-reference-audit
      path: audit.openapi.yaml
      version: 0.27.0
      description: Cloud Events API Product.
      summary: Cloud Events API Product.
    - name: block-storage
      url: just-for-cli-reference-block-storage
      path: block-storage.openapi.yaml
      version: v1
      description: Block Storage API Product
      summary: Block Storage API Product
    - name: container-registry
      url: just-for-cli-reference-container-registry
      path: container-registry.openapi.yaml
      version: 0.1.0
      description: Magalu Container Registry product API.
      summary: Magalu Container Registry product API.
    - name: dbaas
      url: just-for-cli-reference-dbaas
      path: dbaas.openapi.yaml
      version: 1.42.0
      description: DBaaS API Product.
      summary: DBaaS API Product.
    - name: kubernetes
      url: just-for-cli-reference-kubernetes
      path: kubernetes.openapi.yaml
      version: 0.1.0
      description: APIs related to the Kubernetes product.
      summary: APIs related to the Kubernetes product.
    - name: network
      url: just-for-cli-reference-network
      path: network.openapi.yaml
      version: 1.156.0
      description: VPC Api Product
      summary: VPC Api Product
    - name: profile
      url: just-for-cli-reference-profile
      path: profile.openapi.yaml
      version: 0.1.0
      description: Manage users global data
      summary: Manage users global data
    - name: virtual-machine
      url: just-for-cli-reference-virtual-machine
      path: virtual-machine.openapi.yaml
      version: v1
      description: Virtual Machine Api Product
      summary: Virtual Machine Api Product
