openapi: 3.0.3
info:
    title: Global resources management
    description: Manage users global data
    version: 0.1.0
    contact:
        name: Tribo IAAS Cloud
        url: https://gitlab.luizalabs.com/
        email: leandro.poloni@luizalabs.com
paths:
    /v0/ssh-keys:
        post:
            tags:
            - ssh_keys
            summary: Register new SSH key
            description: 'Register new SSH key by providing a name and the public
                SSH key


                The supported key types are: ssh-rsa, ssh-dss, ecdsa-sha, ssh-ed25519,
                sk-ecdsa-sha, sk-ssh-ed25519'
            operationId: create_ssh_key
            security:
            -   OAuth2:
                - gdb:ssh-pkey-w
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/SSHPubKeyPublicInput'
            responses:
                '201':
                    description: Successful Response
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/SSHPubKeyPublicOutput'
                '422':
                    description: Validation Error
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/HTTPValidationError'
        get:
            tags:
            - ssh_keys
            summary: List SSH keys
            description: List the SSH keys. It is possible sort this list with parameters
                id, name, key_type
            operationId: list_ssh_keys
            security:
            -   OAuth2:
                - gdb:ssh-pkey-r
            parameters:
            -   name: _limit
                in: query
                required: false
                schema:
                    type: integer
                    default: 50
                    title: ' Limit'
            -   name: _offset
                in: query
                required: false
                schema:
                    type: integer
                    default: 0
                    title: ' Offset'
            -   name: _sort
                in: query
                required: false
                schema:
                    type: string
                    default: name:asc
                    title: ' Sort'
            responses:
                '200':
                    description: Successful Response
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/SSHPubKeyPublicOutputList'
                '422':
                    description: Validation Error
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/HTTPValidationError'
    /v0/ssh-keys/{key_id}:
        get:
            tags:
            - ssh_keys
            summary: Retrieve a SSH key
            description: Retrieve an SSH key using its ID. If you do not know the
                ID, retrieve it by listing your keys.
            operationId: get_ssh_key
            security:
            -   OAuth2:
                - gdb:ssh-pkey-r
            parameters:
            -   name: key_id
                in: path
                required: true
                schema:
                    type: string
                    format: uuid
                    title: Key Id
            responses:
                '200':
                    description: Successful Response
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/SSHPubKeyPublicOutput'
                    links:
                        delete:
                            operationId: delete_ssh_key
                            description: Delete SSH Key
                            parameters:
                                key_id: $request.path.key_id
                '422':
                    description: Validation Error
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/HTTPValidationError'
        delete:
            tags:
            - ssh_keys
            summary: Delete SSH Key
            description: Delete an SSH key using its id.
            operationId: delete_ssh_key
            security:
            -   OAuth2:
                - gdb:ssh-pkey-w
            parameters:
            -   name: key_id
                in: path
                required: true
                schema:
                    type: string
                    format: uuid
                    title: Key Id
            responses:
                '200':
                    description: Successful Response
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/SSHPubKeyPublicOutput'
                '422':
                    description: Validation Error
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/HTTPValidationError'
    /v0/availability-zones:
        get:
            tags:
            - availability_zones
            summary: List all availability zones.
            description: List all the availability zones
            operationId: list_availability_zones
            security:
            -   OAuth2:
                - gdb:azs-r
            responses:
                '200':
                    description: Successful Response
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/UserRegionsPublicOutput'
                '422':
                    description: Validation Error
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/HTTPValidationError'
components:
    schemas:
        HTTPValidationError:
            properties:
                message:
                    title: Message
                    type: string
                slug:
                    title: Slug
                    type: string
            type: object
            title: HTTPValidationError
            example:
                message: Unauthorized
                slug: Unauthorized
        PublicAZBlockType:
            type: string
            enum:
            - none
            - total
            - read-only
            title: PublicAZBlockType
        SSHPubKeyPublicInput:
            properties:
                name:
                    type: string
                    maxLength: 45
                    title: The SSH Key name
                key:
                    type: string
                    maxLength: 16384
                    title: 'The SSH public key. The supported key types are: ssh-rsa,
                        ssh-dss, ecdsa-sha, ssh-ed25519, sk-ecdsa-sha, sk-ssh-ed25519'
            type: object
            required:
            - name
            - key
            title: SSHPubKeyPublicInput
        SSHPubKeyPublicOutput:
            properties:
                id:
                    type: string
                    format: uuid
                    title: Id
                    example: d77c8402-ef4b-41b0-9cef-b116edf174ab
                name:
                    type: string
                    title: Name
                    example: my-first-key
                key:
                    type: string
                    title: Key
                    example: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCt742ntUIcrMpW7mUXXFgYOAaZC/M4zlEvv60niuXXUHDXr2sq4Uizs1WBdQ4aZrEJnAeHi4DFj5PkPpLdQug5DbpoPbMdaT1BwuaJLaIxBTeq0c2V8GNP/XebPiC1eB+G7L3pWPEbvjpdYnHBxYpSzuJAczh+DKmBs08sbleqUNDkD8f7RsTVSjwpSbpTTxBwn1l1BSs9zcyysxDdAU2r7NtZdVPq6SBCkuCW/dHu6NWWfXgiVCpUKWIHSEWkkFGOFXdB0pPeCgjUG5JLf/BAIfSq/DjJw6Ki7dtezcuz/64Ei8DI5S1ajKfWIWIm5Cb/6gQ2cy0Muh/w+9KsXfbv
                key_type:
                    type: string
                    title: Key Type
                    example: ssh-rsa
            type: object
            required:
            - id
            - name
            - key
            - key_type
            title: SSHPubKeyPublicOutput
        SSHPubKeyPublicOutputList:
            properties:
                results:
                    items:
                        $ref: '#/components/schemas/SSHPubKeyPublicOutput'
                    type: array
                    title: Results
            type: object
            required:
            - results
            title: SSHPubKeyPublicOutputList
        UserAvailabilityZonePublicOutput:
            properties:
                az_id:
                    type: string
                    title: Az Id
                    example: br-se1-a
                block_type:
                    allOf:
                    -   $ref: '#/components/schemas/PublicAZBlockType'
            type: object
            required:
            - az_id
            - block_type
            title: UserAvailabilityZonePublicOutput
        UserRegionPublicOutput:
            properties:
                region_id:
                    type: string
                    title: Region Id
                    example: br-se1
                availability_zones:
                    items:
                        $ref: '#/components/schemas/UserAvailabilityZonePublicOutput'
                    type: array
                    title: Availability Zones
            type: object
            required:
            - region_id
            - availability_zones
            title: UserRegionPublicOutput
        UserRegionsPublicOutput:
            properties:
                results:
                    items:
                        $ref: '#/components/schemas/UserRegionPublicOutput'
                    type: array
                    title: Results
            type: object
            required:
            - results
            title: UserRegionsPublicOutput
        ValidationError:
            properties:
                message:
                    title: Message
                    type: string
                slug:
                    title: Slug
                    type: string
            type: object
            required:
            - loc
            - msg
            - type
            title: ValidationError
            example:
                message: Unauthorized
                slug: Unauthorized
    securitySchemes:
        OAuth2:
            type: oauth2
            flows:
                password:
                    scopes:
                        openid: Default OpenID scope.
                        gdb:ssh-pkey-w: This scope allow the caller to write (create,
                            update, delete) SSH Public Keys for logged tenant, on
                            public GlobalDB
                        gdb:ssh-pkey-r: This scope allow the caller to read SSH Public
                            Keys of logged tenant, on public GlobalDB
                    tokenUrl: https://autoseg-idp.luizalabs.com/oauth/token
tags:
-   name: ssh_keys
    description: Manage SSH Keys
-   name: availability_zones
    description: Manage Availability Zones
servers:
-   url: https://{env}/profile
    variables:
        env:
            description: Environment to use
            default: api.magalu.cloud
            enum:
            - api.magalu.cloud
            - api.pre-prod.jaxyendy.com
            x-mgc-transforms:
            -   type: translate
                translations:
                -   from: prod
                    to: api.magalu.cloud
                -   from: pre-prod
                    to: api.pre-prod.jaxyendy.com
$id: https://globaldb.jaxyendy.com/openapi-cli.json
