modules:
-   description: Block Storage API Product Documentation
    name: block-storage
    path: block-storage.openapi.yaml
    summary: Block Storage API Product Documentation
    super_internal: false
    url: https://block-storage.jaxyendy.com/openapi.json
    version: v1
-   description: Magalu Container Registry product API.
    name: container-registry
    path: container-registry.openapi.yaml
    summary: Magalu Container Registry product API.
    super_internal: false
    url: https://container-registry.jaxyendy.com/openapi.json
    version: 0.1.0
-   description: DBaaS API Product.
    name: dbaas
    path: dbaas.openapi.yaml
    summary: DBaaS API Product.
    super_internal: false
    url: https://dbaas.jaxyendy.com/openapi.json
    version: 1.25.0
-   description: "# Consult API\n\nWith the continued growth of the distributed architecture\
        \ in Magalu\nCloud, everyone should have the ability to audit all (or important)\n\
        events triggered by users or internal systems. This capability is\nessential\
        \ not only for visualizing and tracking changes requested by\ninternal developers\
        \ but also for those made by tenant users. Our\ninitial approach was to create\
        \ a \"broker\" (i.e., an event system and a\nconsultation API) that could\
        \ store all these events. All events are\nexposed using the CloudEvent specification.\n\
        \nThat API is a internal and External (filtered by Tenant ID) usage.\n\n##\
        \ About CloudSpec\nInfo about the spec: https://cloudevents.io/\n\n### The\
        \ cloud spec fields used today ([Spec](https://github.com/cloudevents/spec/blob/main/cloudevents/spec.md)):\n\
        - id: The request id to track.\n- source: Identifies the context of this event.\n\
        - type: The “action” or type of the event. SHOULD be prefixed with a reverse-DNS\
        \ name.\n- specversion: The version of the CloudEvents specification which\
        \ the event uses. Today is 1.0.\n- subject: Identifies the subject of the\
        \ event in the context of the producer. e.g: source\n  is https://virtual-machine.pre-prod.br-se-1.jaxyendy.com/v1/instances/cddd202a-7017-4d80-b702-6c49ad89ae99/start\
        \ and\n  the subject is the instance id.\n- data: Open field with the raw\
        \ event.\n- time: ISO8601 date of the event.\n- authid: An unique identifier\
        \ of the principal that triggered the occurrence.\n- authtype: An enum representing\
        \ the type of principal that triggered the occurrence, e.g: tenant, api_key\
        \ or\n  unauthenticated, system_api_key.\n\n#### Internal Extensions:\n- product:\
        \ Identifies the product formal name, e.g: default, dbass, xaas\n- region:\
        \ The physical region of the event\n- tenantid: Identification of the tenant.\n\
        ## How to Auth\nTo use the API a token is needed, and both grant_types **client_credentials**\
        \ and **authorization_code** tokens can be used.\n\nFollow [this guide](https://magazine.atlassian.net/wiki/spaces/CLOUD/pages/4230643732/Client+Credentials)\
        \ to learn how to authenticate via **client credentials**.\n\nFollow [this\
        \ guide](https://magazine.atlassian.net/wiki/spaces/CLOUD/pages/4253385090/Authorization+Code)\
        \ to learn how to authenticate via **authorization code**.\n"
    name: events
    path: events.openapi.yaml
    summary: "# Consult API\n\nWith the continued growth of the distributed architecture\
        \ in Magalu\nCloud, everyone should have the ability to audit all (or important)\n\
        events triggered by users or internal systems. This capability is\nessential\
        \ not only for visualizing and tracking changes requested by\ninternal developers\
        \ but also for those made by tenant users. Our\ninitial approach was to create\
        \ a \"broker\" (i.e., an event system and a\nconsultation API) that could\
        \ store all these events. All events are\nexposed using the CloudEvent specification.\n\
        \nThat API is a internal and External (filtered by Tenant ID) usage.\n\n##\
        \ About CloudSpec\nInfo about the spec: https://cloudevents.io/\n\n### The\
        \ cloud spec fields used today ([Spec](https://github.com/cloudevents/spec/blob/main/cloudevents/spec.md)):\n\
        - id: The request id to track.\n- source: Identifies the context of this event.\n\
        - type: The “action” or type of the event. SHOULD be prefixed with a reverse-DNS\
        \ name.\n- specversion: The version of the CloudEvents specification which\
        \ the event uses. Today is 1.0.\n- subject: Identifies the subject of the\
        \ event in the context of the producer. e.g: source\n  is https://virtual-machine.pre-prod.br-se-1.jaxyendy.com/v1/instances/cddd202a-7017-4d80-b702-6c49ad89ae99/start\
        \ and\n  the subject is the instance id.\n- data: Open field with the raw\
        \ event.\n- time: ISO8601 date of the event.\n- authid: An unique identifier\
        \ of the principal that triggered the occurrence.\n- authtype: An enum representing\
        \ the type of principal that triggered the occurrence, e.g: tenant, api_key\
        \ or\n  unauthenticated, system_api_key.\n\n#### Internal Extensions:\n- product:\
        \ Identifies the product formal name, e.g: default, dbass, xaas\n- region:\
        \ The physical region of the event\n- tenantid: Identification of the tenant.\n\
        ## How to Auth\nTo use the API a token is needed, and both grant_types **client_credentials**\
        \ and **authorization_code** tokens can be used.\n\nFollow [this guide](https://magazine.atlassian.net/wiki/spaces/CLOUD/pages/4230643732/Client+Credentials)\
        \ to learn how to authenticate via **client credentials**.\n\nFollow [this\
        \ guide](https://magazine.atlassian.net/wiki/spaces/CLOUD/pages/4253385090/Authorization+Code)\
        \ to learn how to authenticate via **authorization code**.\n"
    super_internal: false
    url: https://events-consult-api.jaxyendy.com/
    version: 0.8.0
-   description: APIs related to the Kubernetes product.
    name: kubernetes
    path: kubernetes.openapi.yaml
    summary: APIs related to the Kubernetes product.
    super_internal: false
    url: https://mke.br-ne-1.com/docs/openapi-with-snippets.json
    version: 0.1.0
-   description: APIs referentes ao produto de VPC
    name: network
    path: network.openapi.yaml
    summary: APIs referentes ao produto de VPC
    super_internal: false
    url: https://network.jaxyendy.com/openapi.json
    version: 1.126.1
-   description: Virtual Machine Api Product
    name: virtual-machine
    path: virtual-machine.openapi.yaml
    summary: Virtual Machine Api Product
    super_internal: false
    url: https://virtual-machine.jaxyendy.com/openapi.json
    version: v1
version: 1.0.0
