openapi: 3.0.3
info:
    title: GlobalDB API
    version: 0.1.0
paths:
    /v0/ssh-keys:
        get:
            tags:
            - ssh_keys
            summary: List Ssh Keys
            operationId: list_ssh_keys
            parameters:
            -   name: _limit
                in: query
                required: false
                schema:
                    type: integer
                    title: ' Limit'
                    default: 50
            -   name: _offset
                in: query
                required: false
                schema:
                    type: integer
                    title: ' Offset'
                    default: 0
            -   name: _sort
                in: query
                required: false
                schema:
                    anyOf:
                    -   type: string
                    title: ' Sort'
                    nullable: true
            -   name: X-Tenant-ID
                in: header
                required: true
                schema:
                    type: string
                    title: X-Tenant-Id
                    format: uuid
            responses:
                '200':
                    description: Successful Response
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/SSHPubKeyPublicOutputList'
                '422':
                    description: Validation Error
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/HTTPValidationError'
            security:
            -   OAuth2:
                - gdb:ssh-pkey-r
        post:
            tags:
            - ssh_keys
            summary: Create Ssh Key
            operationId: create_ssh_key
            parameters:
            -   name: X-Tenant-ID
                in: header
                required: true
                schema:
                    type: string
                    title: X-Tenant-Id
                    format: uuid
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/SSHPubKeyPublicInput'
                required: true
            responses:
                '201':
                    description: Successful Response
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/SSHPubKeyPublicOutput'
                '422':
                    description: Validation Error
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/HTTPValidationError'
            security:
            -   OAuth2:
                - gdb:ssh-pkey-w
    /v0/ssh-keys/{key_id}:
        get:
            tags:
            - ssh_keys
            summary: Get Ssh Key
            operationId: get_ssh_key
            parameters:
            -   name: key_id
                in: path
                required: true
                schema:
                    type: string
                    title: Key Id
                    format: uuid
            -   name: X-Tenant-ID
                in: header
                required: true
                schema:
                    type: string
                    title: X-Tenant-Id
                    format: uuid
            responses:
                '200':
                    description: Successful Response
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/SSHPubKeyPublicOutput'
                    links:
                        delete:
                            operationId: delete_ssh_key
                            description: Delete Ssh Key
                            parameters:
                                key_id: $request.path.key_id
                '422':
                    description: Validation Error
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/HTTPValidationError'
            security:
            -   OAuth2:
                - gdb:ssh-pkey-r
        delete:
            tags:
            - ssh_keys
            summary: Delete Ssh Key
            operationId: delete_ssh_key
            parameters:
            -   name: key_id
                in: path
                required: true
                schema:
                    type: string
                    title: Key Id
                    format: uuid
            -   name: X-Tenant-ID
                in: header
                required: true
                schema:
                    type: string
                    title: X-Tenant-Id
                    format: uuid
            responses:
                '200':
                    description: Successful Response
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/SSHPubKeyPublicOutput'
                '422':
                    description: Validation Error
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/HTTPValidationError'
            security:
            -   OAuth2:
                - gdb:ssh-pkey-w
    /healthcheck:
        get:
            summary: Healthcheck
            operationId: healthcheck_healthcheck_get
            responses:
                '200':
                    description: Successful Response
                    content:
                        application/json:
                            schema: {}
            security:
            -   OAuth2:
                - ssh.read
    /metrics:
        get:
            summary: Metrics
            description: Endpoint that serves Prometheus metrics.
            operationId: metrics_metrics_get
            responses:
                '200':
                    description: Successful Response
                    content:
                        application/json:
                            schema: {}
            security:
            -   OAuth2:
                - ssh.read
components:
    schemas:
        HTTPValidationError:
            type: object
            properties:
                message:
                    title: Message
                    type: string
                slug:
                    title: Slug
                    type: string
            title: HTTPValidationError
            example:
                message: Unauthorized
                slug: Unauthorized
        SSHPubKeyPublicInput:
            type: object
            properties:
                name:
                    type: string
                    title: The SSH Key name
                    maxLength: 45
                key:
                    type: string
                    title: The SSH public key data
                    maxLength: 16384
            title: SSHPubKeyPublicInput
            required:
            - name
            - key
        SSHPubKeyPublicOutput:
            type: object
            properties:
                id:
                    type: string
                    title: Id
                    format: uuid
                    example: d77c8402-ef4b-41b0-9cef-b116edf174ab
                name:
                    type: string
                    title: Name
                    example: my-first-key
                key:
                    type: string
                    title: Key
                    example: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCt742ntUIcrMpW7mUXXFgYOAaZC/M4zlEvv60niuXXUHDXr2sq4Uizs1WBdQ4aZrEJnAeHi4DFj5PkPpLdQug5DbpoPbMdaT1BwuaJLaIxBTeq0c2V8GNP/XebPiC1eB+G7L3pWPEbvjpdYnHBxYpSzuJAczh+DKmBs08sbleqUNDkD8f7RsTVSjwpSbpTTxBwn1l1BSs9zcyysxDdAU2r7NtZdVPq6SBCkuCW/dHu6NWWfXgiVCpUKWIHSEWkkFGOFXdB0pPeCgjUG5JLf/BAIfSq/DjJw6Ki7dtezcuz/64Ei8DI5S1ajKfWIWIm5Cb/6gQ2cy0Muh/w+9KsXfbv
                key_type:
                    type: string
                    title: Key Type
                    example: ssh-rsa
            title: SSHPubKeyPublicOutput
            required:
            - id
            - name
            - key
            - key_type
        SSHPubKeyPublicOutputList:
            type: object
            properties:
                results:
                    type: array
                    items:
                        type: object
                        properties:
                            id:
                                type: string
                                title: Id
                                format: uuid
                                example: d77c8402-ef4b-41b0-9cef-b116edf174ab
                            name:
                                type: string
                                title: Name
                                example: my-first-key
                            key:
                                type: string
                                title: Key
                                example: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCt742ntUIcrMpW7mUXXFgYOAaZC/M4zlEvv60niuXXUHDXr2sq4Uizs1WBdQ4aZrEJnAeHi4DFj5PkPpLdQug5DbpoPbMdaT1BwuaJLaIxBTeq0c2V8GNP/XebPiC1eB+G7L3pWPEbvjpdYnHBxYpSzuJAczh+DKmBs08sbleqUNDkD8f7RsTVSjwpSbpTTxBwn1l1BSs9zcyysxDdAU2r7NtZdVPq6SBCkuCW/dHu6NWWfXgiVCpUKWIHSEWkkFGOFXdB0pPeCgjUG5JLf/BAIfSq/DjJw6Ki7dtezcuz/64Ei8DI5S1ajKfWIWIm5Cb/6gQ2cy0Muh/w+9KsXfbv
                            key_type:
                                type: string
                                title: Key Type
                                example: ssh-rsa
                        title: SSHPubKeyPublicOutput
                        required:
                        - id
                        - name
                        - key
                        - key_type
                    title: Results
            title: SSHPubKeyPublicOutputList
            required:
            - results
        ValidationError:
            type: object
            properties:
                message:
                    title: Message
                    type: string
                slug:
                    title: Slug
                    type: string
            title: ValidationError
            required:
            - loc
            - msg
            - type
            example:
                message: Unauthorized
                slug: Unauthorized
tags:
-   name: ssh_keys
    description: ssh_keys
$id: https://globaldb.jaxyendy.com/openapi-cli.json
servers:
-   url: https://{env}/profile
    variables:
        env:
            description: Environment to use
            default: api.magalu.cloud
            enum:
            - api.magalu.cloud
            - api.pre-prod.jaxyendy.com
            x-mgc-transforms:
            -   type: translate
                translations:
                -   from: prod
                    to: api.magalu.cloud
                -   from: pre-prod
                    to: api.pre-prod.jaxyendy.com
