openapi: 3.0.3
info:
    title: GlobalDB API
    description: GlobalDB API
    version: 0.1.0
    contact:
        name: Tribo IAAS Cloud
        url: https://github.com/luizalabs
        email: leandro.poloni@luizalabs.com
paths:
    /v0/ssh-keys:
        post:
            tags:
            - ssh_pub_keys
            summary: Create Ssh Key
            description: Creates a new SSH public key.
            operationId: create_ssh_key
            security:
            -   OAuth2:
                - gdb:ssh-pkey-w
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/SSHPubKeyPublicInput'
            responses:
                '201':
                    description: Successful Response
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/SSHPubKeyPublicOutput'
                '422':
                    description: Validation Error
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/HTTPValidationError'
        get:
            tags:
            - ssh_pub_keys
            summary: List Ssh Keys
            description: Lists all SSH public keys.
            operationId: list_ssh_keys
            security:
            -   OAuth2:
                - gdb:ssh-pkey-r
            parameters:
            -   name: _limit
                in: query
                required: false
                schema:
                    type: integer
                    default: 50
                    title: Limit
                description: Limit the number of results.
            -   name: _offset
                in: query
                required: false
                schema:
                    type: integer
                    default: 0
                    title: Offset
                description: Offset the list of results.
            -   name: _sort
                in: query
                required: false
                schema:
                    type: string
                    title: Sort
                description: Sort the list of results.
            responses:
                '200':
                    description: Successful Response
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/SSHPubKeyPublicOutputList'
                '422':
                    description: Validation Error
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/HTTPValidationError'
    /v0/ssh-keys/{key_name}:
        get:
            tags:
            - ssh_pub_keys
            summary: Get Ssh Key
            description: Retrieves a specific SSH public key.
            operationId: get_ssh_key
            security:
            -   OAuth2:
                - gdb:ssh-pkey-r
            parameters:
            -   name: key_name
                in: path
                required: true
                schema:
                    type: string
                    title: Key Name
                description: The name of the SSH public key.
            responses:
                '200':
                    description: Successful Response
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/SSHPubKeyPublicOutput'
                    links:
                        delete:
                            operationId: delete_ssh_key
                            description: Delete Ssh Key
                            parameters:
                                key_name: $request.path.key_name
                '422':
                    description: Validation Error
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/HTTPValidationError'
        delete:
            tags:
            - ssh_pub_keys
            summary: Delete Ssh Key
            description: Deletes a specific SSH public key.
            operationId: delete_ssh_key
            security:
            -   OAuth2:
                - gdb:ssh-pkey-w
            parameters:
            -   name: key_name
                in: path
                required: true
                schema:
                    type: string
                    title: Key Name
                description: The name of the SSH public key.
            responses:
                '204':
                    description: No Content
components:
    schemas:
        HTTPValidationError:
            properties:
                message:
                    title: Message
                    type: string
                slug:
                    title: Slug
                    type: string
            type: object
            title: HTTPValidationError
            example:
                message: Unauthorized
                slug: Unauthorized
        SSHPubKeyPublicInput:
            properties:
                name:
                    type: string
                    maxLength: 45
                    title: The SSH Key name
                key:
                    type: string
                    maxLength: 16384
                    title: The SSH public key data
            type: object
            required:
            - name
            - key
            title: SSHPubKeyPublicInput
        SSHPubKeyPublicOutput:
            properties:
                name:
                    type: string
                    title: Name
                    example: my-first-key
                key:
                    type: string
                    title: Key
                    example: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCt742ntUIcrMpW7mUXXFgYOAaZC/M4zlEvv60niuXXUHDXr2sq4Uizs1WBdQ4aZrEJnAeHi4DFj5PkPpLdQug5DbpoPbMdaT1BwuaJLaIxBTeq0c2V8GNP/XebPiC1eB+G7L3pWPEbvjpdYnHBxYpSzuJAczh+DKmBs08sbleqUNDkD8f7RsTVSjwpSbpTTxBwn1l1BSs9zcyysxDdAU2r7NtZdVPq6SBCkuCW/dHu6NWWfXgiVCpUKWIHSEWkkFGOFXdB0pPeCgjUG5JLf/BAIfSq/DjJw6Ki7dtezcuz/64Ei8DI5S1ajKfWIWIm5Cb/6gQ2cy0Muh/w+9KsXfbv
                key_type:
                    type: string
                    title: Key Type
                    example: ssh-rsa
            type: object
            required:
            - name
            - key
            - key_type
            title: SSHPubKeyPublicOutput
        SSHPubKeyPublicOutputList:
            properties:
                results:
                    items:
                        $ref: '#/components/schemas/SSHPubKeyPublicOutput'
                    type: array
                    title: Results
            type: object
            required:
            - results
            title: SSHPubKeyPublicOutputList
        ValidationError:
            properties:
                message:
                    title: Message
                    type: string
                slug:
                    title: Slug
                    type: string
            type: object
            required:
            - loc
            - msg
            - type
            title: ValidationError
            example:
                message: Unauthorized
                slug: Unauthorized
    securitySchemes:
        OAuth2:
            description: OAuth2 via IDPA
            flows:
                authorizationCode:
                    authorizationUrl: https://idp-maas-sandbox.ipet.sh/auth/realms/master/protocol/openid-connect/auth
                    scopes:
                        gdb:ssh-pkey-r: Ler na API pública do GlobalDB
                        gdb:ssh-pkey-w: Escrever na API pública do GlobalDB
                    tokenUrl: https://idp-maas-sandbox.ipet.sh/auth/realms/master/protocol/openid-connect/token
            type: oauth2
tags:
-   name: ssh_pub_keys
    description: Operations related to SSH public keys.
servers:
-   url: https://{env}/profile
    variables:
        env:
            description: Environment to use
            default: api.magalu.cloud
            enum:
            - api.magalu.cloud
            - api.pre-prod.jaxyendy.com
            x-mgc-transforms:
            -   type: translate
                translations:
                -   from: prod
                    to: api.magalu.cloud
                -   from: pre-prod
                    to: api.pre-prod.jaxyendy.com
$id: https://globaldb.jaxyendy.com/openapi-cli.json
