name: Project Checks

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

concurrency:
  group: ci-check-${{ github.ref }}

jobs:
  validate:
    name: Project Checks
    runs-on: ${{ vars.RUNNER_RUNS_ON }}
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
        with:
          token: ${{ secrets.GH_PAT2 }}
          fetch-depth: 1
      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 #v5.6.0
        with:
          python-version: "3.12"
          cache: "pip"
      - name: Set up Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 #5.5.0
        with:
          cache-dependency-path: "**/go.sum"
          go-version: ${{ vars.GO_VERSION }}
      - name: "Go Imports"
        run: go install golang.org/x/tools/cmd/goimports@latest
      - uses: pre-commit/action@v3.0.1
        name: "Pre-commit run"
        with:
          extra_args: --show-diff-on-failure --color=always --hook-stage push --all-files
      - name: "Go checks"
        run: make check
