name: Validate Pre Commit Hooks

on:
  push:
    tags:
      - "v*.*.*"
    branches: [ main ]
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

jobs:
  validate:
    name: Run Pre Commit Hooks
    runs-on: self-hosted
    timeout-minutes: 10
    steps:
      - uses: actions/setup-python@v3
      - name: Set owner of working dir recurively (Linux)
        run: sudo chown -R $(whoami) .
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          cache-dependency-path: "**/go.sum"
          go-version: stable
      - name: "Pre-commit"
        run: go install golang.org/x/tools/cmd/goimports@latest
      - uses: pre-commit/action@v3.0.0
        with:
          extra_args: --show-diff-on-failure --color=always --hook-stage push --all-files
