name: Project Checks

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

concurrency:
  group: ci-check-${{ github.ref }}

jobs:
  validate:
    name: Project Checks
    runs-on: ${{ vars.RUNNER_RUNS_ON }}
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
        with:
          token: ${{ secrets.GH_PAT2 }}
          fetch-depth: 1

      - name: Set up Go
        uses: actions/setup-go@v5.0.2
        with:
          cache-dependency-path: "**/go.sum"
          go-version: ${{ vars.GO_VERSION }}
      - name: "Go Imports"
        run: go install golang.org/x/tools/cmd/goimports@latest
      - name: "Pre-commit run"
        run: make pre-commit
      - name: "Go checks"
        run: make check
