name: MGC DEV RELEASE(MANUAL)

on:
  workflow_dispatch:
    inputs:
      input_version:
        description: 'Version to run'
        default: ${{ github.ref_name }}
        required: false
        type: string

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Set owner of working dir recurively (Linux)
        run: sudo chown -R $(whoami) .
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - run: |
          git config --global url."ssh://git@github.com/".insteadOf "https://github.com/"
      - name: Update version.txt
        env:
          GOPRIVATE: "github.com/MagaluCloud/magalu"
      - if: ${{ inputs.username != ''}}
        run: echo "${{ inputs.username }}" > mgc/sdk/version.txt
      - if: ${{ inputs.username == ''}}
        run: echo "${{ github.ref_name }}" > mgc/sdk/version.txt
      - bane: Run codegen
        run: ./scripts/codegen_lib.sh
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean --config="goreleaser_internal_cli.yaml"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          PRIVATE_KEY_PATH: ${{ secrets.SSH_ID_RSA_MAGALUCLI }}
