name: MGC DEV RELEASE(MANUAL)

on:
  workflow_dispatch:
    inputs:
      input_version:
        description: 'Version to run'
        default: ''
        required: false
        type: string

jobs:
  build:
    runs-on: self-hosted
    timeout-minutes: 15
    steps:
      - name: Set owner of working dir recurively (Linux)
        run: sudo chown -R $(whoami) .
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          cache-dependency-path: "**/go.sum"
          go-version: stable
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean --config="goreleaser_internal_cli.yaml"
        env:
          VERSION: ${{ inputs.input_version}}
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          PRIVATE_KEY_PATH: ${{ secrets.SSH_ID_RSA_MAGALUCLI }}
