name: Internal Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to release (e.g., v1.0.0)"
        required: true
        type: string

concurrency:
  group: ci-check-${{ github.ref }}
  
jobs:
  build:
    runs-on: ${{ vars.RUNNER_RUNS_ON }}
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
        with:
          token: ${{ secrets.GH_PAT2 }}
          fetch-depth: 1
      - name: Set up Go
        uses: actions/setup-go@v5.0.2
        with:
          cache-dependency-path: "**/go.sum"
          go-version: ${{ vars.GO_VERSION }} # settings > secrets and variables > variables > GO_VERSION
      - name: Run GoReleaser
        continue-on-error: true
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: 2
          args: release --clean --config="internal.yaml"
        env:
          VERSION: ${{  github.event.inputs.version }}
          GITHUB_TOKEN: ${{ secrets.GH_PAT2 }}
          PRIVATE_KEY_PATH: ${{ secrets.SSH_ID_RSA_MAGALUCLI }}
