name: Release CLI and Terraform

on:
  workflow_dispatch:
    inputs:
      runCLI:
        description: "Run deploy of CLI"
        type: boolean
        required: false
      runTerraform:
        description: "Run deploy of Terraform"
        type: boolean
        required: false

concurrency:
  group: ci-check-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: self-hosted
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 1
          token: ${{ secrets.GH_PAT }}
      - name: Set up Go
        uses: actions/setup-go@v5.0.2
        with:
          cache-dependency-path: "**/go.sum"
          go-version: stable
      - name: Check version candidate
        run: ./scripts/check_release_v2.sh ${{ github.ref_name }}
      - run: go version

  cli-release:
    needs: build
    runs-on: self-hosted
    timeout-minutes: 10
    if: ${{ inputs.runCLI }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PAT }}
      - name: Set up Go
        uses: actions/setup-go@v5.0.2
        with:
          cache-dependency-path: "**/go.sum"
          go-version: stable
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: '2'
          args: release --clean --config="goreleaser_cli.yaml"
        env:
          VERSION: ${{ github.ref_name }}
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          PRIVATE_KEY_PATH: ${{ secrets.SSH_ID_RSA_MAGALUCLI }}

  terraform-release:
    needs: build
    runs-on: self-hosted
    timeout-minutes: 20
    if: ${{ inputs.runTerraform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PAT }}
      - name: Set up Go
        uses: actions/setup-go@v5.0.2
        with:
          cache-dependency-path: "**/go.sum"
          go-version: stable
      - name: Import GPG key
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --batch --yes --passphrase "${{ secrets.GPG_PASSPHRASE }}" --import
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: 2
          args: release --clean --config="goreleaser_terraform.yaml"
        env:
          VERSION: ${{ github.ref_name }}
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          GPG_FINGERPRINT: ${{ secrets.GPG_FINGERPRINT }}
          GPG_PASSPHRASE: ${{ secrets.PASSPHRASE }}
