name: Release CLI

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to release (e.g., v1.0.0)"
        required: true
        type: string

concurrency:
  group: ci-check-${{ github.ref }}

jobs:
  build:
    runs-on: ${{ vars.RUNNER_RUNS_ON }}
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 1
          token: ${{ secrets.GH_PAT2 }}
      - name: Set up Go
        uses: actions/setup-go@v5.0.2
        with:
          cache-dependency-path: "**/go.sum"
          go-version: ${{ vars.GO_VERSION }} # settings > secrets and variables > variables > GO_VERSION
      - name: Check version candidate
        run: ./scripts/check_release_v2.sh ${{ github.ref_name }}
      - run: go version

  cli-release:
    needs: build
    runs-on: ${{ vars.RUNNER_RUNS_ON }}
    timeout-minutes: 10
    if: ${{ inputs.runCLI }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PAT2 }}
      - name: Set up Go
        uses: actions/setup-go@v5.0.2
        with:
          cache-dependency-path: "**/go.sum"
          go-version: ${{ vars.GO_VERSION }} # settings > secrets and variables > variables > GO_VERSION
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: '2'
          args: release --clean --config="release.yaml"
        env:
          VERSION: ${{ github.ref_name }}
          GITHUB_TOKEN: ${{ secrets.GH_PAT2 }}
          PRIVATE_KEY_PATH: ${{ secrets.SSH_ID_RSA_MAGALUCLI }}
      - name: Set up Git config
        run: |
          git config --global user.name "Magalu Cloud"
          git config --global user.email "magalucloud.services@luizalabs.com"
      - name: Setup GitHub CLI
        uses: ksivamuthu/actions-setup-gh-cli@v3
      - name: Create Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT2 }}
        run: |
          gh pr create \
            --repo MagaluCloud/homebrew-mgccli \
            --title "🚀 Update mgccli brew formula to version ${{ github.ref_name }}" \
            --body "This PR updates the mgccli formula to version ${{ github.ref_name }}." \
            --base main \
            --head mgccli-${{ github.ref_name }}
