name: Project Tests

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

concurrency:
  group: ci-check-${{ github.ref }}

jobs:
  test:
    name: Project Checks
    runs-on: ${{ vars.RUNNER_RUNS_ON || 'ubuntu-latest' }}
    timeout-minutes: 60
    
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 1
          
      - name: Set up Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          cache-dependency-path: "**/go.sum"
          go-version: ${{ vars.GO_VERSION || '1.24.2' }}
          
      - name: "Go build"
        run: make build-cicd

      - name: Set MGC Profiles
        env:
          PROFILE_NAME: ${{ inputs.profile_name || 'default' }}
          ACCESS_KEY: ${{ secrets.MGC_ACCESS_KEY || '' }}
          SECRET_KEY: ${{ secrets.MGC_SECRET_KEY || ''}}
        run: |
          # Criar diretório do perfil
          PROFILE_DIR="$HOME/.config/mgc/$PROFILE_NAME"
          echo "Criando diretório: $PROFILE_DIR"
          mkdir -p "$PROFILE_DIR"

          # Criar auth.yaml
          AUTH_FILE="$PROFILE_DIR/auth.yaml"
          echo "Criando arquivo de autenticação: $AUTH_FILE"
          cat > "$AUTH_FILE" << EOF
          access_key_id: $ACCESS_KEY
          secret_access_key: $SECRET_KEY
          EOF

      - name: Run tests
        uses: MagaluCloud/mgccli-tests@v0.0.11
        env:
          MGC_API_KEY: ${{ secrets.MGC_API_KEY || '' }}
          MGC_PATH: "mgc/cli/mgc" # ${{ github.workspace }}/${{ vars.MGC_PATH || 'mgc' }}