name: Project Tests

on:
  workflow_dispatch:

concurrency:
  group: ci-check-${{ github.ref }}

jobs:
  test:
    name: Project Checks
    runs-on: ${{ vars.RUNNER_RUNS_ON }}
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          token: ${{ secrets.GH_PAT2 }}
          fetch-depth: 1

      - name: Set up Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          cache-dependency-path: "**/go.sum"
          go-version: ${{ vars.GO_VERSION }}
      
      - name: "Go build"
        run: make build-cicd

      - name: Run tests
        uses: MagaluCloud/mgccli-tests@v0.0.1
        env:
          MGC_API_KEY: ${{ secrets.MGC_API_KEY }}
          MGC_PATH: ${{ vars.MGC_PATH }}